// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAddress = "address"

// Address mapped from table <address>
type Address struct {
	ID          string         `gorm:"column:id;type:character varying;primaryKey" json:"id"`
	CustomerID  string         `gorm:"column:customer_id;type:character varying;index:IDX_9c9614b2f9d01665800ea8dbff,priority:1" json:"customer_id"`
	Company     string         `gorm:"column:company;type:character varying" json:"company"`
	FirstName   string         `gorm:"column:first_name;type:character varying" json:"first_name"`
	LastName    string         `gorm:"column:last_name;type:character varying" json:"last_name"`
	Address1    string         `gorm:"column:address_1;type:character varying" json:"address_1"`
	Address2    string         `gorm:"column:address_2;type:character varying" json:"address_2"`
	City        string         `gorm:"column:city;type:character varying" json:"city"`
	CountryCode string         `gorm:"column:country_code;type:character varying" json:"country_code"`
	Province    string         `gorm:"column:province;type:character varying" json:"province"`
	PostalCode  string         `gorm:"column:postal_code;type:character varying" json:"postal_code"`
	Phone       string         `gorm:"column:phone;type:character varying" json:"phone"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	Metadata    string         `gorm:"column:metadata;type:jsonb" json:"metadata"`
}

// TableName Address's table name
func (*Address) TableName() string {
	return TableNameAddress
}
