// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCartGiftCard = "cart_gift_cards"

// CartGiftCard mapped from table <cart_gift_cards>
type CartGiftCard struct {
	CartID     string `gorm:"column:cart_id;type:character varying;primaryKey;index:IDX_d38047a90f3d42f0be7909e8ae,priority:1" json:"cart_id"`
	GiftCardID string `gorm:"column:gift_card_id;type:character varying;primaryKey;index:IDX_0fb38b6d167793192bc126d835,priority:1" json:"gift_card_id"`
}

// TableName CartGiftCard's table name
func (*CartGiftCard) TableName() string {
	return TableNameCartGiftCard
}
