// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameClaimTag = "claim_tag"

// ClaimTag mapped from table <claim_tag>
type ClaimTag struct {
	ID        string         `gorm:"column:id;type:character varying;primaryKey" json:"id"`
	Value     string         `gorm:"column:value;type:character varying;not null;index:IDX_ec10c54769877840c132260e4a,priority:1" json:"value"`
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	Metadata  string         `gorm:"column:metadata;type:jsonb" json:"metadata"`
}

// TableName ClaimTag's table name
func (*ClaimTag) TableName() string {
	return TableNameClaimTag
}
