// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCustomShippingOption = "custom_shipping_option"

// CustomShippingOption mapped from table <custom_shipping_option>
type CustomShippingOption struct {
	ID               string         `gorm:"column:id;type:character varying;primaryKey" json:"id"`
	Price            int32          `gorm:"column:price;type:integer;not null" json:"price"`
	ShippingOptionID string         `gorm:"column:shipping_option_id;type:character varying;not null;uniqueIndex:UQ_0f838b122a9a01d921aa1cdb669,priority:1;index:IDX_44090cb11b06174cbcc667e91c,priority:1" json:"shipping_option_id"`
	CartID           string         `gorm:"column:cart_id;type:character varying;uniqueIndex:UQ_0f838b122a9a01d921aa1cdb669,priority:2;index:IDX_93caeb1bb70d37c1d36d6701a7,priority:1" json:"cart_id"`
	CreatedAt        time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt        time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	Metadata         string         `gorm:"column:metadata;type:jsonb" json:"metadata"`
}

// TableName CustomShippingOption's table name
func (*CustomShippingOption) TableName() string {
	return TableNameCustomShippingOption
}
