// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCustomer = "customer"

// Customer mapped from table <customer>
type Customer struct {
	ID               string         `gorm:"column:id;type:character varying;primaryKey" json:"id"`
	Email            string         `gorm:"column:email;type:character varying;not null;uniqueIndex:UQ_unique_email_for_guests_and_customer_accounts,priority:1" json:"email"`
	FirstName        string         `gorm:"column:first_name;type:character varying" json:"first_name"`
	LastName         string         `gorm:"column:last_name;type:character varying" json:"last_name"`
	BillingAddressID string         `gorm:"column:billing_address_id;type:character varying;uniqueIndex:REL_8abe81b9aac151ae60bf507ad1,priority:1;index:IDX_8abe81b9aac151ae60bf507ad1,priority:1" json:"billing_address_id"`
	PasswordHash     string         `gorm:"column:password_hash;type:character varying" json:"password_hash"`
	Phone            string         `gorm:"column:phone;type:character varying" json:"phone"`
	HasAccount       bool           `gorm:"column:has_account;type:boolean;not null;uniqueIndex:UQ_unique_email_for_guests_and_customer_accounts,priority:2" json:"has_account"`
	CreatedAt        time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt        time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	Metadata         string         `gorm:"column:metadata;type:jsonb" json:"metadata"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
