// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCustomerGroupCustomer = "customer_group_customers"

// CustomerGroupCustomer mapped from table <customer_group_customers>
type CustomerGroupCustomer struct {
	CustomerGroupID string `gorm:"column:customer_group_id;type:character varying;primaryKey;index:IDX_620330964db8d2999e67b0dbe3,priority:1" json:"customer_group_id"`
	CustomerID      string `gorm:"column:customer_id;type:character varying;primaryKey;index:IDX_3c6412d076292f439269abe1a2,priority:1" json:"customer_id"`
}

// TableName CustomerGroupCustomer's table name
func (*CustomerGroupCustomer) TableName() string {
	return TableNameCustomerGroupCustomer
}
