// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDiscountConditionProductType = "discount_condition_product_type"

// DiscountConditionProductType mapped from table <discount_condition_product_type>
type DiscountConditionProductType struct {
	ProductTypeID string    `gorm:"column:product_type_id;type:character varying;primaryKey;index:IDX_e706deb68f52ab2756119b9e70,priority:1" json:"product_type_id"`
	ConditionID   string    `gorm:"column:condition_id;type:character varying;primaryKey;index:IDX_6ef23ce0b1d9cf9b5b833e52b9,priority:1" json:"condition_id"`
	CreatedAt     time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	Metadata      string    `gorm:"column:metadata;type:jsonb" json:"metadata"`
}

// TableName DiscountConditionProductType's table name
func (*DiscountConditionProductType) TableName() string {
	return TableNameDiscountConditionProductType
}
