// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDiscount = "discount"

// Discount mapped from table <discount>
type Discount struct {
	ID               string         `gorm:"column:id;type:character varying;primaryKey" json:"id"`
	Code             string         `gorm:"column:code;type:character varying;not null;uniqueIndex:IDX_f65bf52e2239ace276ece2b2f4,priority:1" json:"code"`
	IsDynamic        bool           `gorm:"column:is_dynamic;type:boolean;not null" json:"is_dynamic"`
	RuleID           string         `gorm:"column:rule_id;type:character varying;index:IDX_ac2c280de3701b2d66f6817f76,priority:1" json:"rule_id"`
	IsDisabled       bool           `gorm:"column:is_disabled;type:boolean;not null" json:"is_disabled"`
	ParentDiscountID string         `gorm:"column:parent_discount_id;type:character varying" json:"parent_discount_id"`
	StartsAt         time.Time      `gorm:"column:starts_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP" json:"starts_at"`
	EndsAt           time.Time      `gorm:"column:ends_at;type:timestamp with time zone" json:"ends_at"`
	CreatedAt        time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt        time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	Metadata         string         `gorm:"column:metadata;type:jsonb" json:"metadata"`
	UsageLimit       int32          `gorm:"column:usage_limit;type:integer" json:"usage_limit"`
	UsageCount       int32          `gorm:"column:usage_count;type:integer;not null" json:"usage_count"`
	ValidDuration    string         `gorm:"column:valid_duration;type:character varying" json:"valid_duration"`
}

// TableName Discount's table name
func (*Discount) TableName() string {
	return TableNameDiscount
}
