// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDiscountConditionCustomerGroup = "discount_condition_customer_group"

// DiscountConditionCustomerGroup mapped from table <discount_condition_customer_group>
type DiscountConditionCustomerGroup struct {
	CustomerGroupID string    `gorm:"column:customer_group_id;type:character varying;primaryKey;index:IDX_4d5f98645a67545d8dea42e2eb,priority:1" json:"customer_group_id"`
	ConditionID     string    `gorm:"column:condition_id;type:character varying;primaryKey;index:IDX_8486ee16e69013c645d0b8716b,priority:1" json:"condition_id"`
	CreatedAt       time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	Metadata        string    `gorm:"column:metadata;type:jsonb" json:"metadata"`
}

// TableName DiscountConditionCustomerGroup's table name
func (*DiscountConditionCustomerGroup) TableName() string {
	return TableNameDiscountConditionCustomerGroup
}
