// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFulfillmentItem = "fulfillment_item"

// FulfillmentItem mapped from table <fulfillment_item>
type FulfillmentItem struct {
	FulfillmentID string `gorm:"column:fulfillment_id;type:character varying;primaryKey" json:"fulfillment_id"`
	ItemID        string `gorm:"column:item_id;type:character varying;primaryKey" json:"item_id"`
	Quantity      int32  `gorm:"column:quantity;type:integer;not null" json:"quantity"`
}

// TableName FulfillmentItem's table name
func (*FulfillmentItem) TableName() string {
	return TableNameFulfillmentItem
}
