// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameIdempotencyKey = "idempotency_key"

// IdempotencyKey mapped from table <idempotency_key>
type IdempotencyKey struct {
	ID             string    `gorm:"column:id;type:character varying;primaryKey" json:"id"`
	IdempotencyKey string    `gorm:"column:idempotency_key;type:character varying;not null;uniqueIndex:IDX_a421bf4588d0004a9b0c0fe84f,priority:1" json:"idempotency_key"`
	CreatedAt      time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	LockedAt       time.Time `gorm:"column:locked_at;type:timestamp with time zone" json:"locked_at"`
	RequestMethod  string    `gorm:"column:request_method;type:character varying" json:"request_method"`
	RequestParams  string    `gorm:"column:request_params;type:jsonb" json:"request_params"`
	RequestPath    string    `gorm:"column:request_path;type:character varying" json:"request_path"`
	ResponseCode   int32     `gorm:"column:response_code;type:integer" json:"response_code"`
	ResponseBody   string    `gorm:"column:response_body;type:jsonb" json:"response_body"`
	RecoveryPoint  string    `gorm:"column:recovery_point;type:character varying;not null;default:started" json:"recovery_point"`
}

// TableName IdempotencyKey's table name
func (*IdempotencyKey) TableName() string {
	return TableNameIdempotencyKey
}
