// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLineItem = "line_item"

// LineItem mapped from table <line_item>
type LineItem struct {
	ID                string    `gorm:"column:id;type:character varying;primaryKey" json:"id"`
	CartID            string    `gorm:"column:cart_id;type:character varying;index:IDX_27283ee631862266d0f1c68064,priority:1" json:"cart_id"`
	OrderID           string    `gorm:"column:order_id;type:character varying;index:IDX_43a2b24495fe1d9fc2a9c835bc,priority:1" json:"order_id"`
	SwapID            string    `gorm:"column:swap_id;type:character varying;index:IDX_3fa354d8d1233ff81097b2fcb6,priority:1" json:"swap_id"`
	Title             string    `gorm:"column:title;type:character varying;not null" json:"title"`
	Description       string    `gorm:"column:description;type:character varying" json:"description"`
	Thumbnail         string    `gorm:"column:thumbnail;type:character varying" json:"thumbnail"`
	IsGiftcard        bool      `gorm:"column:is_giftcard;type:boolean;not null" json:"is_giftcard"`
	ShouldMerge       bool      `gorm:"column:should_merge;type:boolean;not null;default:true" json:"should_merge"`
	AllowDiscounts    bool      `gorm:"column:allow_discounts;type:boolean;not null;default:true" json:"allow_discounts"`
	HasShipping       bool      `gorm:"column:has_shipping;type:boolean" json:"has_shipping"`
	UnitPrice         int32     `gorm:"column:unit_price;type:integer;not null" json:"unit_price"`
	VariantID         string    `gorm:"column:variant_id;type:character varying;index:IDX_5371cbaa3be5200f373d24e3d5,priority:1" json:"variant_id"`
	Quantity          int32     `gorm:"column:quantity;type:integer;not null" json:"quantity"`
	FulfilledQuantity int32     `gorm:"column:fulfilled_quantity;type:integer" json:"fulfilled_quantity"`
	ReturnedQuantity  int32     `gorm:"column:returned_quantity;type:integer" json:"returned_quantity"`
	ShippedQuantity   int32     `gorm:"column:shipped_quantity;type:integer" json:"shipped_quantity"`
	CreatedAt         time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	Metadata          string    `gorm:"column:metadata;type:jsonb" json:"metadata"`
	ClaimOrderID      string    `gorm:"column:claim_order_id;type:character varying;index:IDX_118e3c48f09a7728f41023c94e,priority:1" json:"claim_order_id"`
	IsReturn          bool      `gorm:"column:is_return;type:boolean;not null" json:"is_return"`
	OriginalItemID    string    `gorm:"column:original_item_id;type:character varying;uniqueIndex:unique_li_original_item_id_order_edit_id,priority:1" json:"original_item_id"`
	OrderEditID       string    `gorm:"column:order_edit_id;type:character varying;uniqueIndex:unique_li_original_item_id_order_edit_id,priority:2" json:"order_edit_id"`
}

// TableName LineItem's table name
func (*LineItem) TableName() string {
	return TableNameLineItem
}
