// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMoneyAmount = "money_amount"

// MoneyAmount mapped from table <money_amount>
type MoneyAmount struct {
	ID           string         `gorm:"column:id;type:character varying;primaryKey" json:"id"`
	CurrencyCode string         `gorm:"column:currency_code;type:character varying;not null;index:IDX_money_amount_currency_code,priority:1" json:"currency_code"`
	Amount       int32          `gorm:"column:amount;type:integer;not null" json:"amount"`
	RegionID     string         `gorm:"column:region_id;type:character varying;index:idx_money_amount_region_id,priority:1" json:"region_id"`
	CreatedAt    time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	MinQuantity  int32          `gorm:"column:min_quantity;type:integer" json:"min_quantity"`
	MaxQuantity  int32          `gorm:"column:max_quantity;type:integer" json:"max_quantity"`
	PriceListID  string         `gorm:"column:price_list_id;type:character varying" json:"price_list_id"`
}

// TableName MoneyAmount's table name
func (*MoneyAmount) TableName() string {
	return TableNameMoneyAmount
}
