// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNotificationProvider = "notification_provider"

// NotificationProvider mapped from table <notification_provider>
type NotificationProvider struct {
	ID          string `gorm:"column:id;type:character varying;primaryKey" json:"id"`
	IsInstalled bool   `gorm:"column:is_installed;type:boolean;not null;default:true" json:"is_installed"`
}

// TableName NotificationProvider's table name
func (*NotificationProvider) TableName() string {
	return TableNameNotificationProvider
}
