// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNotification = "notification"

// Notification mapped from table <notification>
type Notification struct {
	ID           string    `gorm:"column:id;type:character varying;primaryKey" json:"id"`
	EventName    string    `gorm:"column:event_name;type:character varying" json:"event_name"`
	ResourceType string    `gorm:"column:resource_type;type:character varying;not null;index:IDX_df1494d263740fcfb1d09a98fc,priority:1" json:"resource_type"`
	ResourceID   string    `gorm:"column:resource_id;type:character varying;not null;index:IDX_ea6a358d9ce41c16499aae55f9,priority:1" json:"resource_id"`
	CustomerID   string    `gorm:"column:customer_id;type:character varying;index:IDX_b5df0f53a74b9d0c0a2b652c88,priority:1" json:"customer_id"`
	To           string    `gorm:"column:to;type:character varying;not null" json:"to"`
	Data         string    `gorm:"column:data;type:jsonb;not null" json:"data"`
	ParentID     string    `gorm:"column:parent_id;type:character varying" json:"parent_id"`
	ProviderID   string    `gorm:"column:provider_id;type:character varying" json:"provider_id"`
	CreatedAt    time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

// TableName Notification's table name
func (*Notification) TableName() string {
	return TableNameNotification
}
