// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePaymentSession = "payment_session"

// PaymentSession mapped from table <payment_session>
type PaymentSession struct {
	ID                  string    `gorm:"column:id;type:character varying;primaryKey" json:"id"`
	CartID              string    `gorm:"column:cart_id;type:character varying;uniqueIndex:OneSelected,priority:1;uniqueIndex:UniqPaymentSessionCartIdProviderId,priority:1;index:IDX_d25ba0787e1510ddc5d442ebcf,priority:1" json:"cart_id"`
	ProviderID          string    `gorm:"column:provider_id;type:character varying;not null;uniqueIndex:UniqPaymentSessionCartIdProviderId,priority:2;index:IDX_d18ad72f2fb7c87f075825b6f8,priority:1" json:"provider_id"`
	IsSelected          bool      `gorm:"column:is_selected;type:boolean;uniqueIndex:OneSelected,priority:2" json:"is_selected"`
	Status              string    `gorm:"column:status;type:payment_session_status_enum;not null" json:"status"`
	Data                string    `gorm:"column:data;type:jsonb;not null" json:"data"`
	CreatedAt           time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt           time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	IdempotencyKey      string    `gorm:"column:idempotency_key;type:character varying" json:"idempotency_key"`
	PaymentAuthorizedAt time.Time `gorm:"column:payment_authorized_at;type:timestamp with time zone" json:"payment_authorized_at"`
	Amount              int32     `gorm:"column:amount;type:integer" json:"amount"`
	IsInitiated         bool      `gorm:"column:is_initiated;type:boolean;not null" json:"is_initiated"`
}

// TableName PaymentSession's table name
func (*PaymentSession) TableName() string {
	return TableNamePaymentSession
}
