// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProductImage = "product_images"

// ProductImage mapped from table <product_images>
type ProductImage struct {
	ProductID string `gorm:"column:product_id;type:character varying;primaryKey;index:IDX_4f166bb8c2bfcef2498d97b406,priority:1" json:"product_id"`
	ImageID   string `gorm:"column:image_id;type:character varying;primaryKey;index:IDX_2212515ba306c79f42c46a99db,priority:1" json:"image_id"`
}

// TableName ProductImage's table name
func (*ProductImage) TableName() string {
	return TableNameProductImage
}
