// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameProductVariantMoneyAmount = "product_variant_money_amount"

// ProductVariantMoneyAmount mapped from table <product_variant_money_amount>
type ProductVariantMoneyAmount struct {
	ID            string         `gorm:"column:id;type:character varying;primaryKey" json:"id"`
	MoneyAmountID string         `gorm:"column:money_amount_id;type:text;not null;uniqueIndex:idx_product_variant_money_amount_money_amount_id_unique,priority:1" json:"money_amount_id"`
	VariantID     string         `gorm:"column:variant_id;type:text;not null;index:idx_product_variant_money_amount_variant_id,priority:1" json:"variant_id"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	CreatedAt     time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

// TableName ProductVariantMoneyAmount's table name
func (*ProductVariantMoneyAmount) TableName() string {
	return TableNameProductVariantMoneyAmount
}
