// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameProduct = "product"

// Product mapped from table <product>
type Product struct {
	ID            string         `gorm:"column:id;type:character varying;primaryKey" json:"id"`
	Title         string         `gorm:"column:title;type:character varying;not null;index:idx_gin_product_title,priority:1" json:"title"`
	Subtitle      string         `gorm:"column:subtitle;type:character varying" json:"subtitle"`
	Description   string         `gorm:"column:description;type:character varying;index:idx_gin_product_description,priority:1" json:"description"`
	Handle        string         `gorm:"column:handle;type:character varying;uniqueIndex:IDX_cf9cc6c3f2e6414b992223fff1,priority:1" json:"handle"`
	IsGiftcard    bool           `gorm:"column:is_giftcard;type:boolean;not null" json:"is_giftcard"`
	Thumbnail     string         `gorm:"column:thumbnail;type:character varying" json:"thumbnail"`
	Weight        int32          `gorm:"column:weight;type:integer" json:"weight"`
	Length        int32          `gorm:"column:length;type:integer" json:"length"`
	Height        int32          `gorm:"column:height;type:integer" json:"height"`
	Width         int32          `gorm:"column:width;type:integer" json:"width"`
	HsCode        string         `gorm:"column:hs_code;type:character varying" json:"hs_code"`
	OriginCountry string         `gorm:"column:origin_country;type:character varying" json:"origin_country"`
	MidCode       string         `gorm:"column:mid_code;type:character varying" json:"mid_code"`
	Material      string         `gorm:"column:material;type:character varying" json:"material"`
	CreatedAt     time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	Metadata      string         `gorm:"column:metadata;type:jsonb" json:"metadata"`
	CollectionID  string         `gorm:"column:collection_id;type:character varying" json:"collection_id"`
	TypeID        string         `gorm:"column:type_id;type:character varying" json:"type_id"`
	Discountable  bool           `gorm:"column:discountable;type:boolean;not null;default:true" json:"discountable"`
	Status        string         `gorm:"column:status;type:product_status_enum;not null;default:draft" json:"status"`
	ExternalID    string         `gorm:"column:external_id;type:character varying" json:"external_id"`
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
