// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProductTypeTaxRate = "product_type_tax_rate"

// ProductTypeTaxRate mapped from table <product_type_tax_rate>
type ProductTypeTaxRate struct {
	ProductTypeID string    `gorm:"column:product_type_id;type:character varying;primaryKey;index:IDX_25a3138bb236f63d9bb6c8ff11,priority:1" json:"product_type_id"`
	RateID        string    `gorm:"column:rate_id;type:character varying;primaryKey;index:IDX_ece65a774192b34253abc4cd67,priority:1" json:"rate_id"`
	CreatedAt     time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	Metadata      string    `gorm:"column:metadata;type:jsonb" json:"metadata"`
}

// TableName ProductTypeTaxRate's table name
func (*ProductTypeTaxRate) TableName() string {
	return TableNameProductTypeTaxRate
}
