// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePublishableAPIKeySalesChannel = "publishable_api_key_sales_channel"

// PublishableAPIKeySalesChannel mapped from table <publishable_api_key_sales_channel>
type PublishableAPIKeySalesChannel struct {
	SalesChannelID   string `gorm:"column:sales_channel_id;type:character varying;primaryKey" json:"sales_channel_id"`
	PublishableKeyID string `gorm:"column:publishable_key_id;type:character varying;primaryKey" json:"publishable_key_id"`
}

// TableName PublishableAPIKeySalesChannel's table name
func (*PublishableAPIKeySalesChannel) TableName() string {
	return TableNamePublishableAPIKeySalesChannel
}
