// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePublishableAPIKey = "publishable_api_key"

// PublishableAPIKey mapped from table <publishable_api_key>
type PublishableAPIKey struct {
	ID        string    `gorm:"column:id;type:character varying;primaryKey" json:"id"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	CreatedBy string    `gorm:"column:created_by;type:character varying" json:"created_by"`
	RevokedBy string    `gorm:"column:revoked_by;type:character varying" json:"revoked_by"`
	RevokedAt time.Time `gorm:"column:revoked_at;type:timestamp with time zone" json:"revoked_at"`
	Title     string    `gorm:"column:title;type:character varying;not null" json:"title"`
}

// TableName PublishableAPIKey's table name
func (*PublishableAPIKey) TableName() string {
	return TableNamePublishableAPIKey
}
