// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRegionPaymentProvider = "region_payment_providers"

// RegionPaymentProvider mapped from table <region_payment_providers>
type RegionPaymentProvider struct {
	RegionID   string `gorm:"column:region_id;type:character varying;primaryKey;index:IDX_8aaa78ba90d3802edac317df86,priority:1" json:"region_id"`
	ProviderID string `gorm:"column:provider_id;type:character varying;primaryKey;index:IDX_3a6947180aeec283cd92c59ebb,priority:1" json:"provider_id"`
}

// TableName RegionPaymentProvider's table name
func (*RegionPaymentProvider) TableName() string {
	return TableNameRegionPaymentProvider
}
