// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSalesChannel = "sales_channel"

// SalesChannel mapped from table <sales_channel>
type SalesChannel struct {
	ID          string         `gorm:"column:id;type:character varying;primaryKey" json:"id"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	Name        string         `gorm:"column:name;type:character varying;not null" json:"name"`
	Description string         `gorm:"column:description;type:character varying" json:"description"`
	IsDisabled  bool           `gorm:"column:is_disabled;type:boolean;not null" json:"is_disabled"`
	Metadata    string         `gorm:"column:metadata;type:jsonb" json:"metadata"`
}

// TableName SalesChannel's table name
func (*SalesChannel) TableName() string {
	return TableNameSalesChannel
}
