// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStagedJob = "staged_job"

// StagedJob mapped from table <staged_job>
type StagedJob struct {
	ID        string `gorm:"column:id;type:character varying;primaryKey" json:"id"`
	EventName string `gorm:"column:event_name;type:character varying;not null" json:"event_name"`
	Data      string `gorm:"column:data;type:jsonb;not null" json:"data"`
	Options   string `gorm:"column:options;type:jsonb;not null;default:{}" json:"options"`
}

// TableName StagedJob's table name
func (*StagedJob) TableName() string {
	return TableNameStagedJob
}
