// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTrackingLink = "tracking_link"

// TrackingLink mapped from table <tracking_link>
type TrackingLink struct {
	ID             string         `gorm:"column:id;type:character varying;primaryKey" json:"id"`
	URL            string         `gorm:"column:url;type:character varying" json:"url"`
	TrackingNumber string         `gorm:"column:tracking_number;type:character varying;not null" json:"tracking_number"`
	FulfillmentID  string         `gorm:"column:fulfillment_id;type:character varying;not null" json:"fulfillment_id"`
	CreatedAt      time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	Metadata       string         `gorm:"column:metadata;type:jsonb" json:"metadata"`
	IdempotencyKey string         `gorm:"column:idempotency_key;type:character varying" json:"idempotency_key"`
}

// TableName TrackingLink's table name
func (*TrackingLink) TableName() string {
	return TableNameTrackingLink
}
