package registry

import (
	"context"
)

func New(ctx context.Context) *Base {
	registry := NewRegistry()

	if err := registry.Init(ctx); err != nil {
		registry.Logger().Fatal(err)
	}

	if registry.Config().Applictaion.Preload {
		CallRegistry(registry)
	}

	return registry
}

func CallRegistry(r *Base) {
	r.Context()

	r.Middleware()

	//Repository
	r.AddressRepository()
	r.AnalyticsConfigRepository()
	r.BatchJobRepository()
	r.CartRepository()
	r.ClaimImageRepository()
	r.ClaimItemRepository()
	r.ClaimTagRepository()
	r.ClaimRepository()
	r.CountryRepository()
	r.CurrencyRepository()
	r.CustomShippingOptionRepository()
	r.CustomerGroupRepository()
	r.CustomerRepository()
	r.DiscountConditionRepository()
	r.DiscountRuleRepository()
	r.DiscountRepository()
	r.DraftOrderRepository()
	r.FulfillmentProviderRepository()
	r.FulfillmentRepository()
	r.GiftCardTransactionRepository()
	r.GiftCardRepository()
	r.IdempotencyKeyRepository()
	r.ImageRepository()
	r.InviteRepository()
	r.LineItemAdjustmentRepository()
	r.LineItemTaxLineRepository()
	r.LineItemRepository()
	r.MoneyAmountRepository()
	r.NoteRepository()
	r.NotificationProviderRepository()
	r.NotificationRepository()
	r.OAuthRepository()
	r.OrderEditRepository()
	r.OrderItemChangeRepository()
	r.OrderRepository()
	r.PaymentCollectionRepository()
	r.PaymentProviderRepository()
	r.PaymentSessionRepository()
	r.PaymentRepository()
	r.PriceListRepository()
	r.ProductCategoryRepository()
	r.ProductCollectionRepository()
	r.ProductOptionValueRepository()
	r.ProductOptionRepository()
	r.ProductTagRepository()
	r.ProductTaxRateRepository()
	r.ProductTypeRepository()
	r.ProductVariantInventoryItemRepository()
	r.ProductVariantRepository()
	r.ProductRepository()
	r.PublishableApiKeySalesChannelRepository()
	r.PublishableApiKeyRepository()
	r.RefundRepository()
	r.RegionRepository()
	r.ReturnItemRepository()
	r.ReturnReasonRepository()
	r.ReturnRepository()
	r.SalesChannelLocationRepository()
	r.SalesChannelRepository()
	r.ShippingMethodTaxLineRepository()
	r.ShippingMethodRepository()
	r.ShippingOptionRequirementRepository()
	r.ShippingOptionRepository()
	r.ShippingProfileRepository()
	r.ShippingTaxRateRepository()
	r.StagedJobRepository()
	r.StoreRepository()
	r.SwapRepository()
	r.TaxProviderRepository()
	r.TaxRateRepository()
	r.TrackingLinkRepository()
	r.UserRepository()

	//Services
	r.AnalyticsConfigService()
	r.AuthService()
	r.BatchJobService()
	r.CartService()
	r.ClaimItemService()
	r.ClaimService()
	r.CsvParserService()
	r.CurrencyService()
	r.CustomShippingOptionService()
	r.CustomerGroupService()
	r.CustomerService()
	r.DiscountConditionService()
	r.DiscountService()
	r.DraftOrderService()
	r.EventBus()
	r.DefaultFileService()
	r.FulfillmentProviderService()
	r.FulfillmentService()
	r.GiftCardService()
	r.IdempotencyKeyService()
	r.InviteService()
	r.LineItemAdjustmentService()
	r.LineItemService()
	r.NewTotalsService()
	r.NoteService()
	r.NotificationService()
	r.OAuthService()
	r.OrderItemChangeService()
	r.OrderEditService()
	r.OrderService()
	r.PaymentCollectionService()
	r.PaymentProviderService()
	r.PaymentService()
	r.PriceListService()
	r.PricingService()
	r.ProductCategoryService()
	r.ProductCollectionService()
	r.ProductTagService()
	r.ProductTaxRateService()
	r.ProductTypeService()
	r.ProductVariantInventoryService()
	r.ProductVariantService()
	r.ProductService()
	r.PublishableApiKeyService()
	r.RegionService()
	r.ReturnReasonService()
	r.ReturnService()
	r.SalesChannelInventoryService()
	r.SalesChannelLocationService()
	r.SalesChannelService()
	r.DefaultSearchService()
	r.ShippingOptionService()
	r.ShippingProfileService()
	r.ShippingTaxRateService()
	r.StagedJobService()
	r.StoreService()
	r.StrategyResolverService()
	r.SwapService()
	r.SystemProviderService()
	r.SystemTaxService()
	r.TaxProviderService()
	r.TaxRateService()
	r.TockenService()
	r.TotalsService()
	r.UserService()
}
