// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/driver005/gateway/model"
)

func newCartShippingMethodAdjustment(db *gorm.DB, opts ...gen.DOOption) cartShippingMethodAdjustment {
	_cartShippingMethodAdjustment := cartShippingMethodAdjustment{}

	_cartShippingMethodAdjustment.cartShippingMethodAdjustmentDo.UseDB(db, opts...)
	_cartShippingMethodAdjustment.cartShippingMethodAdjustmentDo.UseModel(&model.CartShippingMethodAdjustment{})

	tableName := _cartShippingMethodAdjustment.cartShippingMethodAdjustmentDo.TableName()
	_cartShippingMethodAdjustment.ALL = field.NewAsterisk(tableName)
	_cartShippingMethodAdjustment.ID = field.NewString(tableName, "id")
	_cartShippingMethodAdjustment.Description = field.NewString(tableName, "description")
	_cartShippingMethodAdjustment.PromotionID = field.NewString(tableName, "promotion_id")
	_cartShippingMethodAdjustment.Code = field.NewString(tableName, "code")
	_cartShippingMethodAdjustment.Amount = field.NewFloat64(tableName, "amount")
	_cartShippingMethodAdjustment.ProviderID = field.NewString(tableName, "provider_id")
	_cartShippingMethodAdjustment.CreatedAt = field.NewTime(tableName, "created_at")
	_cartShippingMethodAdjustment.UpdatedAt = field.NewTime(tableName, "updated_at")
	_cartShippingMethodAdjustment.ShippingMethodID = field.NewString(tableName, "shipping_method_id")

	_cartShippingMethodAdjustment.fillFieldMap()

	return _cartShippingMethodAdjustment
}

type cartShippingMethodAdjustment struct {
	cartShippingMethodAdjustmentDo cartShippingMethodAdjustmentDo

	ALL              field.Asterisk
	ID               field.String
	Description      field.String
	PromotionID      field.String
	Code             field.String
	Amount           field.Float64
	ProviderID       field.String
	CreatedAt        field.Time
	UpdatedAt        field.Time
	ShippingMethodID field.String

	fieldMap map[string]field.Expr
}

func (c cartShippingMethodAdjustment) Table(newTableName string) *cartShippingMethodAdjustment {
	c.cartShippingMethodAdjustmentDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cartShippingMethodAdjustment) As(alias string) *cartShippingMethodAdjustment {
	c.cartShippingMethodAdjustmentDo.DO = *(c.cartShippingMethodAdjustmentDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cartShippingMethodAdjustment) updateTableName(table string) *cartShippingMethodAdjustment {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.Description = field.NewString(table, "description")
	c.PromotionID = field.NewString(table, "promotion_id")
	c.Code = field.NewString(table, "code")
	c.Amount = field.NewFloat64(table, "amount")
	c.ProviderID = field.NewString(table, "provider_id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.ShippingMethodID = field.NewString(table, "shipping_method_id")

	c.fillFieldMap()

	return c
}

func (c *cartShippingMethodAdjustment) WithContext(ctx context.Context) *cartShippingMethodAdjustmentDo {
	return c.cartShippingMethodAdjustmentDo.WithContext(ctx)
}

func (c cartShippingMethodAdjustment) TableName() string {
	return c.cartShippingMethodAdjustmentDo.TableName()
}

func (c cartShippingMethodAdjustment) Alias() string { return c.cartShippingMethodAdjustmentDo.Alias() }

func (c cartShippingMethodAdjustment) Columns(cols ...field.Expr) gen.Columns {
	return c.cartShippingMethodAdjustmentDo.Columns(cols...)
}

func (c *cartShippingMethodAdjustment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cartShippingMethodAdjustment) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 9)
	c.fieldMap["id"] = c.ID
	c.fieldMap["description"] = c.Description
	c.fieldMap["promotion_id"] = c.PromotionID
	c.fieldMap["code"] = c.Code
	c.fieldMap["amount"] = c.Amount
	c.fieldMap["provider_id"] = c.ProviderID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["shipping_method_id"] = c.ShippingMethodID
}

func (c cartShippingMethodAdjustment) clone(db *gorm.DB) cartShippingMethodAdjustment {
	c.cartShippingMethodAdjustmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cartShippingMethodAdjustment) replaceDB(db *gorm.DB) cartShippingMethodAdjustment {
	c.cartShippingMethodAdjustmentDo.ReplaceDB(db)
	return c
}

type cartShippingMethodAdjustmentDo struct{ gen.DO }

func (c cartShippingMethodAdjustmentDo) Debug() *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.Debug())
}

func (c cartShippingMethodAdjustmentDo) WithContext(ctx context.Context) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cartShippingMethodAdjustmentDo) ReadDB() *cartShippingMethodAdjustmentDo {
	return c.Clauses(dbresolver.Read)
}

func (c cartShippingMethodAdjustmentDo) WriteDB() *cartShippingMethodAdjustmentDo {
	return c.Clauses(dbresolver.Write)
}

func (c cartShippingMethodAdjustmentDo) Session(config *gorm.Session) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.Session(config))
}

func (c cartShippingMethodAdjustmentDo) Clauses(conds ...clause.Expression) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cartShippingMethodAdjustmentDo) Returning(value interface{}, columns ...string) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cartShippingMethodAdjustmentDo) Not(conds ...gen.Condition) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cartShippingMethodAdjustmentDo) Or(conds ...gen.Condition) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cartShippingMethodAdjustmentDo) Select(conds ...field.Expr) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cartShippingMethodAdjustmentDo) Where(conds ...gen.Condition) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cartShippingMethodAdjustmentDo) Order(conds ...field.Expr) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cartShippingMethodAdjustmentDo) Distinct(cols ...field.Expr) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cartShippingMethodAdjustmentDo) Omit(cols ...field.Expr) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cartShippingMethodAdjustmentDo) Join(table schema.Tabler, on ...field.Expr) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cartShippingMethodAdjustmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cartShippingMethodAdjustmentDo) RightJoin(table schema.Tabler, on ...field.Expr) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cartShippingMethodAdjustmentDo) Group(cols ...field.Expr) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cartShippingMethodAdjustmentDo) Having(conds ...gen.Condition) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cartShippingMethodAdjustmentDo) Limit(limit int) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cartShippingMethodAdjustmentDo) Offset(offset int) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cartShippingMethodAdjustmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cartShippingMethodAdjustmentDo) Unscoped() *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cartShippingMethodAdjustmentDo) Create(values ...*model.CartShippingMethodAdjustment) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cartShippingMethodAdjustmentDo) CreateInBatches(values []*model.CartShippingMethodAdjustment, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cartShippingMethodAdjustmentDo) Save(values ...*model.CartShippingMethodAdjustment) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cartShippingMethodAdjustmentDo) First() (*model.CartShippingMethodAdjustment, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CartShippingMethodAdjustment), nil
	}
}

func (c cartShippingMethodAdjustmentDo) Take() (*model.CartShippingMethodAdjustment, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CartShippingMethodAdjustment), nil
	}
}

func (c cartShippingMethodAdjustmentDo) Last() (*model.CartShippingMethodAdjustment, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CartShippingMethodAdjustment), nil
	}
}

func (c cartShippingMethodAdjustmentDo) Find() ([]*model.CartShippingMethodAdjustment, error) {
	result, err := c.DO.Find()
	return result.([]*model.CartShippingMethodAdjustment), err
}

func (c cartShippingMethodAdjustmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CartShippingMethodAdjustment, err error) {
	buf := make([]*model.CartShippingMethodAdjustment, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cartShippingMethodAdjustmentDo) FindInBatches(result *[]*model.CartShippingMethodAdjustment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cartShippingMethodAdjustmentDo) Attrs(attrs ...field.AssignExpr) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cartShippingMethodAdjustmentDo) Assign(attrs ...field.AssignExpr) *cartShippingMethodAdjustmentDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cartShippingMethodAdjustmentDo) Joins(fields ...field.RelationField) *cartShippingMethodAdjustmentDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cartShippingMethodAdjustmentDo) Preload(fields ...field.RelationField) *cartShippingMethodAdjustmentDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cartShippingMethodAdjustmentDo) FirstOrInit() (*model.CartShippingMethodAdjustment, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CartShippingMethodAdjustment), nil
	}
}

func (c cartShippingMethodAdjustmentDo) FirstOrCreate() (*model.CartShippingMethodAdjustment, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CartShippingMethodAdjustment), nil
	}
}

func (c cartShippingMethodAdjustmentDo) FindByPage(offset int, limit int) (result []*model.CartShippingMethodAdjustment, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cartShippingMethodAdjustmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cartShippingMethodAdjustmentDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cartShippingMethodAdjustmentDo) Delete(models ...*model.CartShippingMethodAdjustment) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cartShippingMethodAdjustmentDo) withDO(do gen.Dao) *cartShippingMethodAdjustmentDo {
	c.DO = *do.(*gen.DO)
	return c
}
