// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/driver005/gateway/model"
)

func newCartSalesChannel(db *gorm.DB, opts ...gen.DOOption) cartSalesChannel {
	_cartSalesChannel := cartSalesChannel{}

	_cartSalesChannel.cartSalesChannelDo.UseDB(db, opts...)
	_cartSalesChannel.cartSalesChannelDo.UseModel(&model.CartSalesChannel{})

	tableName := _cartSalesChannel.cartSalesChannelDo.TableName()
	_cartSalesChannel.ALL = field.NewAsterisk(tableName)
	_cartSalesChannel.ID = field.NewString(tableName, "id")
	_cartSalesChannel.CartID = field.NewString(tableName, "cart_id")
	_cartSalesChannel.SalesChannelID = field.NewString(tableName, "sales_channel_id")
	_cartSalesChannel.CreatedAt = field.NewTime(tableName, "created_at")
	_cartSalesChannel.UpdatedAt = field.NewTime(tableName, "updated_at")
	_cartSalesChannel.DeletedAt = field.NewField(tableName, "deleted_at")

	_cartSalesChannel.fillFieldMap()

	return _cartSalesChannel
}

type cartSalesChannel struct {
	cartSalesChannelDo cartSalesChannelDo

	ALL            field.Asterisk
	ID             field.String
	CartID         field.String
	SalesChannelID field.String
	CreatedAt      field.Time
	UpdatedAt      field.Time
	DeletedAt      field.Field

	fieldMap map[string]field.Expr
}

func (c cartSalesChannel) Table(newTableName string) *cartSalesChannel {
	c.cartSalesChannelDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cartSalesChannel) As(alias string) *cartSalesChannel {
	c.cartSalesChannelDo.DO = *(c.cartSalesChannelDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cartSalesChannel) updateTableName(table string) *cartSalesChannel {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.CartID = field.NewString(table, "cart_id")
	c.SalesChannelID = field.NewString(table, "sales_channel_id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")

	c.fillFieldMap()

	return c
}

func (c *cartSalesChannel) WithContext(ctx context.Context) *cartSalesChannelDo {
	return c.cartSalesChannelDo.WithContext(ctx)
}

func (c cartSalesChannel) TableName() string { return c.cartSalesChannelDo.TableName() }

func (c cartSalesChannel) Alias() string { return c.cartSalesChannelDo.Alias() }

func (c cartSalesChannel) Columns(cols ...field.Expr) gen.Columns {
	return c.cartSalesChannelDo.Columns(cols...)
}

func (c *cartSalesChannel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cartSalesChannel) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 6)
	c.fieldMap["id"] = c.ID
	c.fieldMap["cart_id"] = c.CartID
	c.fieldMap["sales_channel_id"] = c.SalesChannelID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
}

func (c cartSalesChannel) clone(db *gorm.DB) cartSalesChannel {
	c.cartSalesChannelDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cartSalesChannel) replaceDB(db *gorm.DB) cartSalesChannel {
	c.cartSalesChannelDo.ReplaceDB(db)
	return c
}

type cartSalesChannelDo struct{ gen.DO }

func (c cartSalesChannelDo) Debug() *cartSalesChannelDo {
	return c.withDO(c.DO.Debug())
}

func (c cartSalesChannelDo) WithContext(ctx context.Context) *cartSalesChannelDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cartSalesChannelDo) ReadDB() *cartSalesChannelDo {
	return c.Clauses(dbresolver.Read)
}

func (c cartSalesChannelDo) WriteDB() *cartSalesChannelDo {
	return c.Clauses(dbresolver.Write)
}

func (c cartSalesChannelDo) Session(config *gorm.Session) *cartSalesChannelDo {
	return c.withDO(c.DO.Session(config))
}

func (c cartSalesChannelDo) Clauses(conds ...clause.Expression) *cartSalesChannelDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cartSalesChannelDo) Returning(value interface{}, columns ...string) *cartSalesChannelDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cartSalesChannelDo) Not(conds ...gen.Condition) *cartSalesChannelDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cartSalesChannelDo) Or(conds ...gen.Condition) *cartSalesChannelDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cartSalesChannelDo) Select(conds ...field.Expr) *cartSalesChannelDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cartSalesChannelDo) Where(conds ...gen.Condition) *cartSalesChannelDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cartSalesChannelDo) Order(conds ...field.Expr) *cartSalesChannelDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cartSalesChannelDo) Distinct(cols ...field.Expr) *cartSalesChannelDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cartSalesChannelDo) Omit(cols ...field.Expr) *cartSalesChannelDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cartSalesChannelDo) Join(table schema.Tabler, on ...field.Expr) *cartSalesChannelDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cartSalesChannelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cartSalesChannelDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cartSalesChannelDo) RightJoin(table schema.Tabler, on ...field.Expr) *cartSalesChannelDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cartSalesChannelDo) Group(cols ...field.Expr) *cartSalesChannelDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cartSalesChannelDo) Having(conds ...gen.Condition) *cartSalesChannelDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cartSalesChannelDo) Limit(limit int) *cartSalesChannelDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cartSalesChannelDo) Offset(offset int) *cartSalesChannelDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cartSalesChannelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cartSalesChannelDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cartSalesChannelDo) Unscoped() *cartSalesChannelDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cartSalesChannelDo) Create(values ...*model.CartSalesChannel) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cartSalesChannelDo) CreateInBatches(values []*model.CartSalesChannel, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cartSalesChannelDo) Save(values ...*model.CartSalesChannel) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cartSalesChannelDo) First() (*model.CartSalesChannel, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CartSalesChannel), nil
	}
}

func (c cartSalesChannelDo) Take() (*model.CartSalesChannel, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CartSalesChannel), nil
	}
}

func (c cartSalesChannelDo) Last() (*model.CartSalesChannel, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CartSalesChannel), nil
	}
}

func (c cartSalesChannelDo) Find() ([]*model.CartSalesChannel, error) {
	result, err := c.DO.Find()
	return result.([]*model.CartSalesChannel), err
}

func (c cartSalesChannelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CartSalesChannel, err error) {
	buf := make([]*model.CartSalesChannel, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cartSalesChannelDo) FindInBatches(result *[]*model.CartSalesChannel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cartSalesChannelDo) Attrs(attrs ...field.AssignExpr) *cartSalesChannelDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cartSalesChannelDo) Assign(attrs ...field.AssignExpr) *cartSalesChannelDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cartSalesChannelDo) Joins(fields ...field.RelationField) *cartSalesChannelDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cartSalesChannelDo) Preload(fields ...field.RelationField) *cartSalesChannelDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cartSalesChannelDo) FirstOrInit() (*model.CartSalesChannel, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CartSalesChannel), nil
	}
}

func (c cartSalesChannelDo) FirstOrCreate() (*model.CartSalesChannel, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CartSalesChannel), nil
	}
}

func (c cartSalesChannelDo) FindByPage(offset int, limit int) (result []*model.CartSalesChannel, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cartSalesChannelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cartSalesChannelDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cartSalesChannelDo) Delete(models ...*model.CartSalesChannel) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cartSalesChannelDo) withDO(do gen.Dao) *cartSalesChannelDo {
	c.DO = *do.(*gen.DO)
	return c
}
