// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/driver005/gateway/model"
)

func newClaimItemTag(db *gorm.DB, opts ...gen.DOOption) claimItemTag {
	_claimItemTag := claimItemTag{}

	_claimItemTag.claimItemTagDo.UseDB(db, opts...)
	_claimItemTag.claimItemTagDo.UseModel(&model.ClaimItemTag{})

	tableName := _claimItemTag.claimItemTagDo.TableName()
	_claimItemTag.ALL = field.NewAsterisk(tableName)
	_claimItemTag.ItemID = field.NewString(tableName, "item_id")
	_claimItemTag.TagID = field.NewString(tableName, "tag_id")

	_claimItemTag.fillFieldMap()

	return _claimItemTag
}

type claimItemTag struct {
	claimItemTagDo claimItemTagDo

	ALL    field.Asterisk
	ItemID field.String
	TagID  field.String

	fieldMap map[string]field.Expr
}

func (c claimItemTag) Table(newTableName string) *claimItemTag {
	c.claimItemTagDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c claimItemTag) As(alias string) *claimItemTag {
	c.claimItemTagDo.DO = *(c.claimItemTagDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *claimItemTag) updateTableName(table string) *claimItemTag {
	c.ALL = field.NewAsterisk(table)
	c.ItemID = field.NewString(table, "item_id")
	c.TagID = field.NewString(table, "tag_id")

	c.fillFieldMap()

	return c
}

func (c *claimItemTag) WithContext(ctx context.Context) *claimItemTagDo {
	return c.claimItemTagDo.WithContext(ctx)
}

func (c claimItemTag) TableName() string { return c.claimItemTagDo.TableName() }

func (c claimItemTag) Alias() string { return c.claimItemTagDo.Alias() }

func (c claimItemTag) Columns(cols ...field.Expr) gen.Columns {
	return c.claimItemTagDo.Columns(cols...)
}

func (c *claimItemTag) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *claimItemTag) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 2)
	c.fieldMap["item_id"] = c.ItemID
	c.fieldMap["tag_id"] = c.TagID
}

func (c claimItemTag) clone(db *gorm.DB) claimItemTag {
	c.claimItemTagDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c claimItemTag) replaceDB(db *gorm.DB) claimItemTag {
	c.claimItemTagDo.ReplaceDB(db)
	return c
}

type claimItemTagDo struct{ gen.DO }

func (c claimItemTagDo) Debug() *claimItemTagDo {
	return c.withDO(c.DO.Debug())
}

func (c claimItemTagDo) WithContext(ctx context.Context) *claimItemTagDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c claimItemTagDo) ReadDB() *claimItemTagDo {
	return c.Clauses(dbresolver.Read)
}

func (c claimItemTagDo) WriteDB() *claimItemTagDo {
	return c.Clauses(dbresolver.Write)
}

func (c claimItemTagDo) Session(config *gorm.Session) *claimItemTagDo {
	return c.withDO(c.DO.Session(config))
}

func (c claimItemTagDo) Clauses(conds ...clause.Expression) *claimItemTagDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c claimItemTagDo) Returning(value interface{}, columns ...string) *claimItemTagDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c claimItemTagDo) Not(conds ...gen.Condition) *claimItemTagDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c claimItemTagDo) Or(conds ...gen.Condition) *claimItemTagDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c claimItemTagDo) Select(conds ...field.Expr) *claimItemTagDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c claimItemTagDo) Where(conds ...gen.Condition) *claimItemTagDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c claimItemTagDo) Order(conds ...field.Expr) *claimItemTagDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c claimItemTagDo) Distinct(cols ...field.Expr) *claimItemTagDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c claimItemTagDo) Omit(cols ...field.Expr) *claimItemTagDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c claimItemTagDo) Join(table schema.Tabler, on ...field.Expr) *claimItemTagDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c claimItemTagDo) LeftJoin(table schema.Tabler, on ...field.Expr) *claimItemTagDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c claimItemTagDo) RightJoin(table schema.Tabler, on ...field.Expr) *claimItemTagDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c claimItemTagDo) Group(cols ...field.Expr) *claimItemTagDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c claimItemTagDo) Having(conds ...gen.Condition) *claimItemTagDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c claimItemTagDo) Limit(limit int) *claimItemTagDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c claimItemTagDo) Offset(offset int) *claimItemTagDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c claimItemTagDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *claimItemTagDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c claimItemTagDo) Unscoped() *claimItemTagDo {
	return c.withDO(c.DO.Unscoped())
}

func (c claimItemTagDo) Create(values ...*model.ClaimItemTag) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c claimItemTagDo) CreateInBatches(values []*model.ClaimItemTag, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c claimItemTagDo) Save(values ...*model.ClaimItemTag) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c claimItemTagDo) First() (*model.ClaimItemTag, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ClaimItemTag), nil
	}
}

func (c claimItemTagDo) Take() (*model.ClaimItemTag, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ClaimItemTag), nil
	}
}

func (c claimItemTagDo) Last() (*model.ClaimItemTag, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ClaimItemTag), nil
	}
}

func (c claimItemTagDo) Find() ([]*model.ClaimItemTag, error) {
	result, err := c.DO.Find()
	return result.([]*model.ClaimItemTag), err
}

func (c claimItemTagDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ClaimItemTag, err error) {
	buf := make([]*model.ClaimItemTag, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c claimItemTagDo) FindInBatches(result *[]*model.ClaimItemTag, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c claimItemTagDo) Attrs(attrs ...field.AssignExpr) *claimItemTagDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c claimItemTagDo) Assign(attrs ...field.AssignExpr) *claimItemTagDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c claimItemTagDo) Joins(fields ...field.RelationField) *claimItemTagDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c claimItemTagDo) Preload(fields ...field.RelationField) *claimItemTagDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c claimItemTagDo) FirstOrInit() (*model.ClaimItemTag, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ClaimItemTag), nil
	}
}

func (c claimItemTagDo) FirstOrCreate() (*model.ClaimItemTag, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ClaimItemTag), nil
	}
}

func (c claimItemTagDo) FindByPage(offset int, limit int) (result []*model.ClaimItemTag, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c claimItemTagDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c claimItemTagDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c claimItemTagDo) Delete(models ...*model.ClaimItemTag) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *claimItemTagDo) withDO(do gen.Dao) *claimItemTagDo {
	c.DO = *do.(*gen.DO)
	return c
}
