// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/driver005/gateway/model"
)

func newCustomShippingOption(db *gorm.DB, opts ...gen.DOOption) customShippingOption {
	_customShippingOption := customShippingOption{}

	_customShippingOption.customShippingOptionDo.UseDB(db, opts...)
	_customShippingOption.customShippingOptionDo.UseModel(&model.CustomShippingOption{})

	tableName := _customShippingOption.customShippingOptionDo.TableName()
	_customShippingOption.ALL = field.NewAsterisk(tableName)
	_customShippingOption.ID = field.NewString(tableName, "id")
	_customShippingOption.Price = field.NewInt32(tableName, "price")
	_customShippingOption.ShippingOptionID = field.NewString(tableName, "shipping_option_id")
	_customShippingOption.CartID = field.NewString(tableName, "cart_id")
	_customShippingOption.CreatedAt = field.NewTime(tableName, "created_at")
	_customShippingOption.UpdatedAt = field.NewTime(tableName, "updated_at")
	_customShippingOption.DeletedAt = field.NewField(tableName, "deleted_at")
	_customShippingOption.Metadata = field.NewString(tableName, "metadata")

	_customShippingOption.fillFieldMap()

	return _customShippingOption
}

type customShippingOption struct {
	customShippingOptionDo customShippingOptionDo

	ALL              field.Asterisk
	ID               field.String
	Price            field.Int32
	ShippingOptionID field.String
	CartID           field.String
	CreatedAt        field.Time
	UpdatedAt        field.Time
	DeletedAt        field.Field
	Metadata         field.String

	fieldMap map[string]field.Expr
}

func (c customShippingOption) Table(newTableName string) *customShippingOption {
	c.customShippingOptionDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c customShippingOption) As(alias string) *customShippingOption {
	c.customShippingOptionDo.DO = *(c.customShippingOptionDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *customShippingOption) updateTableName(table string) *customShippingOption {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.Price = field.NewInt32(table, "price")
	c.ShippingOptionID = field.NewString(table, "shipping_option_id")
	c.CartID = field.NewString(table, "cart_id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")
	c.Metadata = field.NewString(table, "metadata")

	c.fillFieldMap()

	return c
}

func (c *customShippingOption) WithContext(ctx context.Context) *customShippingOptionDo {
	return c.customShippingOptionDo.WithContext(ctx)
}

func (c customShippingOption) TableName() string { return c.customShippingOptionDo.TableName() }

func (c customShippingOption) Alias() string { return c.customShippingOptionDo.Alias() }

func (c customShippingOption) Columns(cols ...field.Expr) gen.Columns {
	return c.customShippingOptionDo.Columns(cols...)
}

func (c *customShippingOption) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *customShippingOption) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 8)
	c.fieldMap["id"] = c.ID
	c.fieldMap["price"] = c.Price
	c.fieldMap["shipping_option_id"] = c.ShippingOptionID
	c.fieldMap["cart_id"] = c.CartID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
	c.fieldMap["metadata"] = c.Metadata
}

func (c customShippingOption) clone(db *gorm.DB) customShippingOption {
	c.customShippingOptionDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c customShippingOption) replaceDB(db *gorm.DB) customShippingOption {
	c.customShippingOptionDo.ReplaceDB(db)
	return c
}

type customShippingOptionDo struct{ gen.DO }

func (c customShippingOptionDo) Debug() *customShippingOptionDo {
	return c.withDO(c.DO.Debug())
}

func (c customShippingOptionDo) WithContext(ctx context.Context) *customShippingOptionDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c customShippingOptionDo) ReadDB() *customShippingOptionDo {
	return c.Clauses(dbresolver.Read)
}

func (c customShippingOptionDo) WriteDB() *customShippingOptionDo {
	return c.Clauses(dbresolver.Write)
}

func (c customShippingOptionDo) Session(config *gorm.Session) *customShippingOptionDo {
	return c.withDO(c.DO.Session(config))
}

func (c customShippingOptionDo) Clauses(conds ...clause.Expression) *customShippingOptionDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c customShippingOptionDo) Returning(value interface{}, columns ...string) *customShippingOptionDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c customShippingOptionDo) Not(conds ...gen.Condition) *customShippingOptionDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c customShippingOptionDo) Or(conds ...gen.Condition) *customShippingOptionDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c customShippingOptionDo) Select(conds ...field.Expr) *customShippingOptionDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c customShippingOptionDo) Where(conds ...gen.Condition) *customShippingOptionDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c customShippingOptionDo) Order(conds ...field.Expr) *customShippingOptionDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c customShippingOptionDo) Distinct(cols ...field.Expr) *customShippingOptionDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c customShippingOptionDo) Omit(cols ...field.Expr) *customShippingOptionDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c customShippingOptionDo) Join(table schema.Tabler, on ...field.Expr) *customShippingOptionDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c customShippingOptionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *customShippingOptionDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c customShippingOptionDo) RightJoin(table schema.Tabler, on ...field.Expr) *customShippingOptionDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c customShippingOptionDo) Group(cols ...field.Expr) *customShippingOptionDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c customShippingOptionDo) Having(conds ...gen.Condition) *customShippingOptionDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c customShippingOptionDo) Limit(limit int) *customShippingOptionDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c customShippingOptionDo) Offset(offset int) *customShippingOptionDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c customShippingOptionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *customShippingOptionDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c customShippingOptionDo) Unscoped() *customShippingOptionDo {
	return c.withDO(c.DO.Unscoped())
}

func (c customShippingOptionDo) Create(values ...*model.CustomShippingOption) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c customShippingOptionDo) CreateInBatches(values []*model.CustomShippingOption, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c customShippingOptionDo) Save(values ...*model.CustomShippingOption) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c customShippingOptionDo) First() (*model.CustomShippingOption, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CustomShippingOption), nil
	}
}

func (c customShippingOptionDo) Take() (*model.CustomShippingOption, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CustomShippingOption), nil
	}
}

func (c customShippingOptionDo) Last() (*model.CustomShippingOption, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CustomShippingOption), nil
	}
}

func (c customShippingOptionDo) Find() ([]*model.CustomShippingOption, error) {
	result, err := c.DO.Find()
	return result.([]*model.CustomShippingOption), err
}

func (c customShippingOptionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CustomShippingOption, err error) {
	buf := make([]*model.CustomShippingOption, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c customShippingOptionDo) FindInBatches(result *[]*model.CustomShippingOption, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c customShippingOptionDo) Attrs(attrs ...field.AssignExpr) *customShippingOptionDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c customShippingOptionDo) Assign(attrs ...field.AssignExpr) *customShippingOptionDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c customShippingOptionDo) Joins(fields ...field.RelationField) *customShippingOptionDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c customShippingOptionDo) Preload(fields ...field.RelationField) *customShippingOptionDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c customShippingOptionDo) FirstOrInit() (*model.CustomShippingOption, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CustomShippingOption), nil
	}
}

func (c customShippingOptionDo) FirstOrCreate() (*model.CustomShippingOption, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CustomShippingOption), nil
	}
}

func (c customShippingOptionDo) FindByPage(offset int, limit int) (result []*model.CustomShippingOption, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c customShippingOptionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c customShippingOptionDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c customShippingOptionDo) Delete(models ...*model.CustomShippingOption) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *customShippingOptionDo) withDO(do gen.Dao) *customShippingOptionDo {
	c.DO = *do.(*gen.DO)
	return c
}
