// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/driver005/gateway/model"
)

func newDiscountCondition(db *gorm.DB, opts ...gen.DOOption) discountCondition {
	_discountCondition := discountCondition{}

	_discountCondition.discountConditionDo.UseDB(db, opts...)
	_discountCondition.discountConditionDo.UseModel(&model.DiscountCondition{})

	tableName := _discountCondition.discountConditionDo.TableName()
	_discountCondition.ALL = field.NewAsterisk(tableName)
	_discountCondition.ID = field.NewString(tableName, "id")
	_discountCondition.Type = field.NewString(tableName, "type")
	_discountCondition.Operator = field.NewString(tableName, "operator")
	_discountCondition.DiscountRuleID = field.NewString(tableName, "discount_rule_id")
	_discountCondition.CreatedAt = field.NewTime(tableName, "created_at")
	_discountCondition.UpdatedAt = field.NewTime(tableName, "updated_at")
	_discountCondition.DeletedAt = field.NewField(tableName, "deleted_at")
	_discountCondition.Metadata = field.NewString(tableName, "metadata")

	_discountCondition.fillFieldMap()

	return _discountCondition
}

type discountCondition struct {
	discountConditionDo discountConditionDo

	ALL            field.Asterisk
	ID             field.String
	Type           field.String
	Operator       field.String
	DiscountRuleID field.String
	CreatedAt      field.Time
	UpdatedAt      field.Time
	DeletedAt      field.Field
	Metadata       field.String

	fieldMap map[string]field.Expr
}

func (d discountCondition) Table(newTableName string) *discountCondition {
	d.discountConditionDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d discountCondition) As(alias string) *discountCondition {
	d.discountConditionDo.DO = *(d.discountConditionDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *discountCondition) updateTableName(table string) *discountCondition {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewString(table, "id")
	d.Type = field.NewString(table, "type")
	d.Operator = field.NewString(table, "operator")
	d.DiscountRuleID = field.NewString(table, "discount_rule_id")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")
	d.DeletedAt = field.NewField(table, "deleted_at")
	d.Metadata = field.NewString(table, "metadata")

	d.fillFieldMap()

	return d
}

func (d *discountCondition) WithContext(ctx context.Context) *discountConditionDo {
	return d.discountConditionDo.WithContext(ctx)
}

func (d discountCondition) TableName() string { return d.discountConditionDo.TableName() }

func (d discountCondition) Alias() string { return d.discountConditionDo.Alias() }

func (d discountCondition) Columns(cols ...field.Expr) gen.Columns {
	return d.discountConditionDo.Columns(cols...)
}

func (d *discountCondition) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *discountCondition) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 8)
	d.fieldMap["id"] = d.ID
	d.fieldMap["type"] = d.Type
	d.fieldMap["operator"] = d.Operator
	d.fieldMap["discount_rule_id"] = d.DiscountRuleID
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
	d.fieldMap["deleted_at"] = d.DeletedAt
	d.fieldMap["metadata"] = d.Metadata
}

func (d discountCondition) clone(db *gorm.DB) discountCondition {
	d.discountConditionDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d discountCondition) replaceDB(db *gorm.DB) discountCondition {
	d.discountConditionDo.ReplaceDB(db)
	return d
}

type discountConditionDo struct{ gen.DO }

func (d discountConditionDo) Debug() *discountConditionDo {
	return d.withDO(d.DO.Debug())
}

func (d discountConditionDo) WithContext(ctx context.Context) *discountConditionDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d discountConditionDo) ReadDB() *discountConditionDo {
	return d.Clauses(dbresolver.Read)
}

func (d discountConditionDo) WriteDB() *discountConditionDo {
	return d.Clauses(dbresolver.Write)
}

func (d discountConditionDo) Session(config *gorm.Session) *discountConditionDo {
	return d.withDO(d.DO.Session(config))
}

func (d discountConditionDo) Clauses(conds ...clause.Expression) *discountConditionDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d discountConditionDo) Returning(value interface{}, columns ...string) *discountConditionDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d discountConditionDo) Not(conds ...gen.Condition) *discountConditionDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d discountConditionDo) Or(conds ...gen.Condition) *discountConditionDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d discountConditionDo) Select(conds ...field.Expr) *discountConditionDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d discountConditionDo) Where(conds ...gen.Condition) *discountConditionDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d discountConditionDo) Order(conds ...field.Expr) *discountConditionDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d discountConditionDo) Distinct(cols ...field.Expr) *discountConditionDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d discountConditionDo) Omit(cols ...field.Expr) *discountConditionDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d discountConditionDo) Join(table schema.Tabler, on ...field.Expr) *discountConditionDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d discountConditionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *discountConditionDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d discountConditionDo) RightJoin(table schema.Tabler, on ...field.Expr) *discountConditionDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d discountConditionDo) Group(cols ...field.Expr) *discountConditionDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d discountConditionDo) Having(conds ...gen.Condition) *discountConditionDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d discountConditionDo) Limit(limit int) *discountConditionDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d discountConditionDo) Offset(offset int) *discountConditionDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d discountConditionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *discountConditionDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d discountConditionDo) Unscoped() *discountConditionDo {
	return d.withDO(d.DO.Unscoped())
}

func (d discountConditionDo) Create(values ...*model.DiscountCondition) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d discountConditionDo) CreateInBatches(values []*model.DiscountCondition, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d discountConditionDo) Save(values ...*model.DiscountCondition) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d discountConditionDo) First() (*model.DiscountCondition, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DiscountCondition), nil
	}
}

func (d discountConditionDo) Take() (*model.DiscountCondition, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DiscountCondition), nil
	}
}

func (d discountConditionDo) Last() (*model.DiscountCondition, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DiscountCondition), nil
	}
}

func (d discountConditionDo) Find() ([]*model.DiscountCondition, error) {
	result, err := d.DO.Find()
	return result.([]*model.DiscountCondition), err
}

func (d discountConditionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DiscountCondition, err error) {
	buf := make([]*model.DiscountCondition, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d discountConditionDo) FindInBatches(result *[]*model.DiscountCondition, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d discountConditionDo) Attrs(attrs ...field.AssignExpr) *discountConditionDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d discountConditionDo) Assign(attrs ...field.AssignExpr) *discountConditionDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d discountConditionDo) Joins(fields ...field.RelationField) *discountConditionDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d discountConditionDo) Preload(fields ...field.RelationField) *discountConditionDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d discountConditionDo) FirstOrInit() (*model.DiscountCondition, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DiscountCondition), nil
	}
}

func (d discountConditionDo) FirstOrCreate() (*model.DiscountCondition, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DiscountCondition), nil
	}
}

func (d discountConditionDo) FindByPage(offset int, limit int) (result []*model.DiscountCondition, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d discountConditionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d discountConditionDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d discountConditionDo) Delete(models ...*model.DiscountCondition) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *discountConditionDo) withDO(do gen.Dao) *discountConditionDo {
	d.DO = *do.(*gen.DO)
	return d
}
