// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/driver005/gateway/model"
)

func newOrderDiscount(db *gorm.DB, opts ...gen.DOOption) orderDiscount {
	_orderDiscount := orderDiscount{}

	_orderDiscount.orderDiscountDo.UseDB(db, opts...)
	_orderDiscount.orderDiscountDo.UseModel(&model.OrderDiscount{})

	tableName := _orderDiscount.orderDiscountDo.TableName()
	_orderDiscount.ALL = field.NewAsterisk(tableName)
	_orderDiscount.OrderID = field.NewString(tableName, "order_id")
	_orderDiscount.DiscountID = field.NewString(tableName, "discount_id")

	_orderDiscount.fillFieldMap()

	return _orderDiscount
}

type orderDiscount struct {
	orderDiscountDo orderDiscountDo

	ALL        field.Asterisk
	OrderID    field.String
	DiscountID field.String

	fieldMap map[string]field.Expr
}

func (o orderDiscount) Table(newTableName string) *orderDiscount {
	o.orderDiscountDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o orderDiscount) As(alias string) *orderDiscount {
	o.orderDiscountDo.DO = *(o.orderDiscountDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *orderDiscount) updateTableName(table string) *orderDiscount {
	o.ALL = field.NewAsterisk(table)
	o.OrderID = field.NewString(table, "order_id")
	o.DiscountID = field.NewString(table, "discount_id")

	o.fillFieldMap()

	return o
}

func (o *orderDiscount) WithContext(ctx context.Context) *orderDiscountDo {
	return o.orderDiscountDo.WithContext(ctx)
}

func (o orderDiscount) TableName() string { return o.orderDiscountDo.TableName() }

func (o orderDiscount) Alias() string { return o.orderDiscountDo.Alias() }

func (o orderDiscount) Columns(cols ...field.Expr) gen.Columns {
	return o.orderDiscountDo.Columns(cols...)
}

func (o *orderDiscount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *orderDiscount) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 2)
	o.fieldMap["order_id"] = o.OrderID
	o.fieldMap["discount_id"] = o.DiscountID
}

func (o orderDiscount) clone(db *gorm.DB) orderDiscount {
	o.orderDiscountDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o orderDiscount) replaceDB(db *gorm.DB) orderDiscount {
	o.orderDiscountDo.ReplaceDB(db)
	return o
}

type orderDiscountDo struct{ gen.DO }

func (o orderDiscountDo) Debug() *orderDiscountDo {
	return o.withDO(o.DO.Debug())
}

func (o orderDiscountDo) WithContext(ctx context.Context) *orderDiscountDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o orderDiscountDo) ReadDB() *orderDiscountDo {
	return o.Clauses(dbresolver.Read)
}

func (o orderDiscountDo) WriteDB() *orderDiscountDo {
	return o.Clauses(dbresolver.Write)
}

func (o orderDiscountDo) Session(config *gorm.Session) *orderDiscountDo {
	return o.withDO(o.DO.Session(config))
}

func (o orderDiscountDo) Clauses(conds ...clause.Expression) *orderDiscountDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o orderDiscountDo) Returning(value interface{}, columns ...string) *orderDiscountDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o orderDiscountDo) Not(conds ...gen.Condition) *orderDiscountDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o orderDiscountDo) Or(conds ...gen.Condition) *orderDiscountDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o orderDiscountDo) Select(conds ...field.Expr) *orderDiscountDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o orderDiscountDo) Where(conds ...gen.Condition) *orderDiscountDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o orderDiscountDo) Order(conds ...field.Expr) *orderDiscountDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o orderDiscountDo) Distinct(cols ...field.Expr) *orderDiscountDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o orderDiscountDo) Omit(cols ...field.Expr) *orderDiscountDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o orderDiscountDo) Join(table schema.Tabler, on ...field.Expr) *orderDiscountDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o orderDiscountDo) LeftJoin(table schema.Tabler, on ...field.Expr) *orderDiscountDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o orderDiscountDo) RightJoin(table schema.Tabler, on ...field.Expr) *orderDiscountDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o orderDiscountDo) Group(cols ...field.Expr) *orderDiscountDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o orderDiscountDo) Having(conds ...gen.Condition) *orderDiscountDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o orderDiscountDo) Limit(limit int) *orderDiscountDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o orderDiscountDo) Offset(offset int) *orderDiscountDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o orderDiscountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *orderDiscountDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o orderDiscountDo) Unscoped() *orderDiscountDo {
	return o.withDO(o.DO.Unscoped())
}

func (o orderDiscountDo) Create(values ...*model.OrderDiscount) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o orderDiscountDo) CreateInBatches(values []*model.OrderDiscount, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o orderDiscountDo) Save(values ...*model.OrderDiscount) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o orderDiscountDo) First() (*model.OrderDiscount, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderDiscount), nil
	}
}

func (o orderDiscountDo) Take() (*model.OrderDiscount, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderDiscount), nil
	}
}

func (o orderDiscountDo) Last() (*model.OrderDiscount, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderDiscount), nil
	}
}

func (o orderDiscountDo) Find() ([]*model.OrderDiscount, error) {
	result, err := o.DO.Find()
	return result.([]*model.OrderDiscount), err
}

func (o orderDiscountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OrderDiscount, err error) {
	buf := make([]*model.OrderDiscount, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o orderDiscountDo) FindInBatches(result *[]*model.OrderDiscount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o orderDiscountDo) Attrs(attrs ...field.AssignExpr) *orderDiscountDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o orderDiscountDo) Assign(attrs ...field.AssignExpr) *orderDiscountDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o orderDiscountDo) Joins(fields ...field.RelationField) *orderDiscountDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o orderDiscountDo) Preload(fields ...field.RelationField) *orderDiscountDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o orderDiscountDo) FirstOrInit() (*model.OrderDiscount, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderDiscount), nil
	}
}

func (o orderDiscountDo) FirstOrCreate() (*model.OrderDiscount, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderDiscount), nil
	}
}

func (o orderDiscountDo) FindByPage(offset int, limit int) (result []*model.OrderDiscount, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o orderDiscountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o orderDiscountDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o orderDiscountDo) Delete(models ...*model.OrderDiscount) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *orderDiscountDo) withDO(do gen.Dao) *orderDiscountDo {
	o.DO = *do.(*gen.DO)
	return o
}
