// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/driver005/gateway/model"
)

func newOrderSalesChannel(db *gorm.DB, opts ...gen.DOOption) orderSalesChannel {
	_orderSalesChannel := orderSalesChannel{}

	_orderSalesChannel.orderSalesChannelDo.UseDB(db, opts...)
	_orderSalesChannel.orderSalesChannelDo.UseModel(&model.OrderSalesChannel{})

	tableName := _orderSalesChannel.orderSalesChannelDo.TableName()
	_orderSalesChannel.ALL = field.NewAsterisk(tableName)
	_orderSalesChannel.ID = field.NewString(tableName, "id")
	_orderSalesChannel.OrderID = field.NewString(tableName, "order_id")
	_orderSalesChannel.SalesChannelID = field.NewString(tableName, "sales_channel_id")
	_orderSalesChannel.CreatedAt = field.NewTime(tableName, "created_at")
	_orderSalesChannel.UpdatedAt = field.NewTime(tableName, "updated_at")
	_orderSalesChannel.DeletedAt = field.NewField(tableName, "deleted_at")

	_orderSalesChannel.fillFieldMap()

	return _orderSalesChannel
}

type orderSalesChannel struct {
	orderSalesChannelDo orderSalesChannelDo

	ALL            field.Asterisk
	ID             field.String
	OrderID        field.String
	SalesChannelID field.String
	CreatedAt      field.Time
	UpdatedAt      field.Time
	DeletedAt      field.Field

	fieldMap map[string]field.Expr
}

func (o orderSalesChannel) Table(newTableName string) *orderSalesChannel {
	o.orderSalesChannelDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o orderSalesChannel) As(alias string) *orderSalesChannel {
	o.orderSalesChannelDo.DO = *(o.orderSalesChannelDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *orderSalesChannel) updateTableName(table string) *orderSalesChannel {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewString(table, "id")
	o.OrderID = field.NewString(table, "order_id")
	o.SalesChannelID = field.NewString(table, "sales_channel_id")
	o.CreatedAt = field.NewTime(table, "created_at")
	o.UpdatedAt = field.NewTime(table, "updated_at")
	o.DeletedAt = field.NewField(table, "deleted_at")

	o.fillFieldMap()

	return o
}

func (o *orderSalesChannel) WithContext(ctx context.Context) *orderSalesChannelDo {
	return o.orderSalesChannelDo.WithContext(ctx)
}

func (o orderSalesChannel) TableName() string { return o.orderSalesChannelDo.TableName() }

func (o orderSalesChannel) Alias() string { return o.orderSalesChannelDo.Alias() }

func (o orderSalesChannel) Columns(cols ...field.Expr) gen.Columns {
	return o.orderSalesChannelDo.Columns(cols...)
}

func (o *orderSalesChannel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *orderSalesChannel) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 6)
	o.fieldMap["id"] = o.ID
	o.fieldMap["order_id"] = o.OrderID
	o.fieldMap["sales_channel_id"] = o.SalesChannelID
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
	o.fieldMap["deleted_at"] = o.DeletedAt
}

func (o orderSalesChannel) clone(db *gorm.DB) orderSalesChannel {
	o.orderSalesChannelDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o orderSalesChannel) replaceDB(db *gorm.DB) orderSalesChannel {
	o.orderSalesChannelDo.ReplaceDB(db)
	return o
}

type orderSalesChannelDo struct{ gen.DO }

func (o orderSalesChannelDo) Debug() *orderSalesChannelDo {
	return o.withDO(o.DO.Debug())
}

func (o orderSalesChannelDo) WithContext(ctx context.Context) *orderSalesChannelDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o orderSalesChannelDo) ReadDB() *orderSalesChannelDo {
	return o.Clauses(dbresolver.Read)
}

func (o orderSalesChannelDo) WriteDB() *orderSalesChannelDo {
	return o.Clauses(dbresolver.Write)
}

func (o orderSalesChannelDo) Session(config *gorm.Session) *orderSalesChannelDo {
	return o.withDO(o.DO.Session(config))
}

func (o orderSalesChannelDo) Clauses(conds ...clause.Expression) *orderSalesChannelDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o orderSalesChannelDo) Returning(value interface{}, columns ...string) *orderSalesChannelDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o orderSalesChannelDo) Not(conds ...gen.Condition) *orderSalesChannelDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o orderSalesChannelDo) Or(conds ...gen.Condition) *orderSalesChannelDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o orderSalesChannelDo) Select(conds ...field.Expr) *orderSalesChannelDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o orderSalesChannelDo) Where(conds ...gen.Condition) *orderSalesChannelDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o orderSalesChannelDo) Order(conds ...field.Expr) *orderSalesChannelDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o orderSalesChannelDo) Distinct(cols ...field.Expr) *orderSalesChannelDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o orderSalesChannelDo) Omit(cols ...field.Expr) *orderSalesChannelDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o orderSalesChannelDo) Join(table schema.Tabler, on ...field.Expr) *orderSalesChannelDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o orderSalesChannelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *orderSalesChannelDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o orderSalesChannelDo) RightJoin(table schema.Tabler, on ...field.Expr) *orderSalesChannelDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o orderSalesChannelDo) Group(cols ...field.Expr) *orderSalesChannelDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o orderSalesChannelDo) Having(conds ...gen.Condition) *orderSalesChannelDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o orderSalesChannelDo) Limit(limit int) *orderSalesChannelDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o orderSalesChannelDo) Offset(offset int) *orderSalesChannelDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o orderSalesChannelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *orderSalesChannelDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o orderSalesChannelDo) Unscoped() *orderSalesChannelDo {
	return o.withDO(o.DO.Unscoped())
}

func (o orderSalesChannelDo) Create(values ...*model.OrderSalesChannel) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o orderSalesChannelDo) CreateInBatches(values []*model.OrderSalesChannel, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o orderSalesChannelDo) Save(values ...*model.OrderSalesChannel) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o orderSalesChannelDo) First() (*model.OrderSalesChannel, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderSalesChannel), nil
	}
}

func (o orderSalesChannelDo) Take() (*model.OrderSalesChannel, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderSalesChannel), nil
	}
}

func (o orderSalesChannelDo) Last() (*model.OrderSalesChannel, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderSalesChannel), nil
	}
}

func (o orderSalesChannelDo) Find() ([]*model.OrderSalesChannel, error) {
	result, err := o.DO.Find()
	return result.([]*model.OrderSalesChannel), err
}

func (o orderSalesChannelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OrderSalesChannel, err error) {
	buf := make([]*model.OrderSalesChannel, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o orderSalesChannelDo) FindInBatches(result *[]*model.OrderSalesChannel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o orderSalesChannelDo) Attrs(attrs ...field.AssignExpr) *orderSalesChannelDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o orderSalesChannelDo) Assign(attrs ...field.AssignExpr) *orderSalesChannelDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o orderSalesChannelDo) Joins(fields ...field.RelationField) *orderSalesChannelDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o orderSalesChannelDo) Preload(fields ...field.RelationField) *orderSalesChannelDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o orderSalesChannelDo) FirstOrInit() (*model.OrderSalesChannel, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderSalesChannel), nil
	}
}

func (o orderSalesChannelDo) FirstOrCreate() (*model.OrderSalesChannel, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OrderSalesChannel), nil
	}
}

func (o orderSalesChannelDo) FindByPage(offset int, limit int) (result []*model.OrderSalesChannel, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o orderSalesChannelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o orderSalesChannelDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o orderSalesChannelDo) Delete(models ...*model.OrderSalesChannel) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *orderSalesChannelDo) withDO(do gen.Dao) *orderSalesChannelDo {
	o.DO = *do.(*gen.DO)
	return o
}
