// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/driver005/gateway/model"
)

func newPaymentCollectionSession(db *gorm.DB, opts ...gen.DOOption) paymentCollectionSession {
	_paymentCollectionSession := paymentCollectionSession{}

	_paymentCollectionSession.paymentCollectionSessionDo.UseDB(db, opts...)
	_paymentCollectionSession.paymentCollectionSessionDo.UseModel(&model.PaymentCollectionSession{})

	tableName := _paymentCollectionSession.paymentCollectionSessionDo.TableName()
	_paymentCollectionSession.ALL = field.NewAsterisk(tableName)
	_paymentCollectionSession.PaymentCollectionID = field.NewString(tableName, "payment_collection_id")
	_paymentCollectionSession.PaymentSessionID = field.NewString(tableName, "payment_session_id")

	_paymentCollectionSession.fillFieldMap()

	return _paymentCollectionSession
}

type paymentCollectionSession struct {
	paymentCollectionSessionDo paymentCollectionSessionDo

	ALL                 field.Asterisk
	PaymentCollectionID field.String
	PaymentSessionID    field.String

	fieldMap map[string]field.Expr
}

func (p paymentCollectionSession) Table(newTableName string) *paymentCollectionSession {
	p.paymentCollectionSessionDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p paymentCollectionSession) As(alias string) *paymentCollectionSession {
	p.paymentCollectionSessionDo.DO = *(p.paymentCollectionSessionDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *paymentCollectionSession) updateTableName(table string) *paymentCollectionSession {
	p.ALL = field.NewAsterisk(table)
	p.PaymentCollectionID = field.NewString(table, "payment_collection_id")
	p.PaymentSessionID = field.NewString(table, "payment_session_id")

	p.fillFieldMap()

	return p
}

func (p *paymentCollectionSession) WithContext(ctx context.Context) *paymentCollectionSessionDo {
	return p.paymentCollectionSessionDo.WithContext(ctx)
}

func (p paymentCollectionSession) TableName() string { return p.paymentCollectionSessionDo.TableName() }

func (p paymentCollectionSession) Alias() string { return p.paymentCollectionSessionDo.Alias() }

func (p paymentCollectionSession) Columns(cols ...field.Expr) gen.Columns {
	return p.paymentCollectionSessionDo.Columns(cols...)
}

func (p *paymentCollectionSession) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *paymentCollectionSession) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 2)
	p.fieldMap["payment_collection_id"] = p.PaymentCollectionID
	p.fieldMap["payment_session_id"] = p.PaymentSessionID
}

func (p paymentCollectionSession) clone(db *gorm.DB) paymentCollectionSession {
	p.paymentCollectionSessionDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p paymentCollectionSession) replaceDB(db *gorm.DB) paymentCollectionSession {
	p.paymentCollectionSessionDo.ReplaceDB(db)
	return p
}

type paymentCollectionSessionDo struct{ gen.DO }

func (p paymentCollectionSessionDo) Debug() *paymentCollectionSessionDo {
	return p.withDO(p.DO.Debug())
}

func (p paymentCollectionSessionDo) WithContext(ctx context.Context) *paymentCollectionSessionDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p paymentCollectionSessionDo) ReadDB() *paymentCollectionSessionDo {
	return p.Clauses(dbresolver.Read)
}

func (p paymentCollectionSessionDo) WriteDB() *paymentCollectionSessionDo {
	return p.Clauses(dbresolver.Write)
}

func (p paymentCollectionSessionDo) Session(config *gorm.Session) *paymentCollectionSessionDo {
	return p.withDO(p.DO.Session(config))
}

func (p paymentCollectionSessionDo) Clauses(conds ...clause.Expression) *paymentCollectionSessionDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p paymentCollectionSessionDo) Returning(value interface{}, columns ...string) *paymentCollectionSessionDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p paymentCollectionSessionDo) Not(conds ...gen.Condition) *paymentCollectionSessionDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p paymentCollectionSessionDo) Or(conds ...gen.Condition) *paymentCollectionSessionDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p paymentCollectionSessionDo) Select(conds ...field.Expr) *paymentCollectionSessionDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p paymentCollectionSessionDo) Where(conds ...gen.Condition) *paymentCollectionSessionDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p paymentCollectionSessionDo) Order(conds ...field.Expr) *paymentCollectionSessionDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p paymentCollectionSessionDo) Distinct(cols ...field.Expr) *paymentCollectionSessionDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p paymentCollectionSessionDo) Omit(cols ...field.Expr) *paymentCollectionSessionDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p paymentCollectionSessionDo) Join(table schema.Tabler, on ...field.Expr) *paymentCollectionSessionDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p paymentCollectionSessionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *paymentCollectionSessionDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p paymentCollectionSessionDo) RightJoin(table schema.Tabler, on ...field.Expr) *paymentCollectionSessionDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p paymentCollectionSessionDo) Group(cols ...field.Expr) *paymentCollectionSessionDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p paymentCollectionSessionDo) Having(conds ...gen.Condition) *paymentCollectionSessionDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p paymentCollectionSessionDo) Limit(limit int) *paymentCollectionSessionDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p paymentCollectionSessionDo) Offset(offset int) *paymentCollectionSessionDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p paymentCollectionSessionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *paymentCollectionSessionDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p paymentCollectionSessionDo) Unscoped() *paymentCollectionSessionDo {
	return p.withDO(p.DO.Unscoped())
}

func (p paymentCollectionSessionDo) Create(values ...*model.PaymentCollectionSession) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p paymentCollectionSessionDo) CreateInBatches(values []*model.PaymentCollectionSession, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p paymentCollectionSessionDo) Save(values ...*model.PaymentCollectionSession) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p paymentCollectionSessionDo) First() (*model.PaymentCollectionSession, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentCollectionSession), nil
	}
}

func (p paymentCollectionSessionDo) Take() (*model.PaymentCollectionSession, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentCollectionSession), nil
	}
}

func (p paymentCollectionSessionDo) Last() (*model.PaymentCollectionSession, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentCollectionSession), nil
	}
}

func (p paymentCollectionSessionDo) Find() ([]*model.PaymentCollectionSession, error) {
	result, err := p.DO.Find()
	return result.([]*model.PaymentCollectionSession), err
}

func (p paymentCollectionSessionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PaymentCollectionSession, err error) {
	buf := make([]*model.PaymentCollectionSession, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p paymentCollectionSessionDo) FindInBatches(result *[]*model.PaymentCollectionSession, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p paymentCollectionSessionDo) Attrs(attrs ...field.AssignExpr) *paymentCollectionSessionDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p paymentCollectionSessionDo) Assign(attrs ...field.AssignExpr) *paymentCollectionSessionDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p paymentCollectionSessionDo) Joins(fields ...field.RelationField) *paymentCollectionSessionDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p paymentCollectionSessionDo) Preload(fields ...field.RelationField) *paymentCollectionSessionDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p paymentCollectionSessionDo) FirstOrInit() (*model.PaymentCollectionSession, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentCollectionSession), nil
	}
}

func (p paymentCollectionSessionDo) FirstOrCreate() (*model.PaymentCollectionSession, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentCollectionSession), nil
	}
}

func (p paymentCollectionSessionDo) FindByPage(offset int, limit int) (result []*model.PaymentCollectionSession, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p paymentCollectionSessionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p paymentCollectionSessionDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p paymentCollectionSessionDo) Delete(models ...*model.PaymentCollectionSession) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *paymentCollectionSessionDo) withDO(do gen.Dao) *paymentCollectionSessionDo {
	p.DO = *do.(*gen.DO)
	return p
}
