// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/driver005/gateway/model"
)

func newProductTaxRate(db *gorm.DB, opts ...gen.DOOption) productTaxRate {
	_productTaxRate := productTaxRate{}

	_productTaxRate.productTaxRateDo.UseDB(db, opts...)
	_productTaxRate.productTaxRateDo.UseModel(&model.ProductTaxRate{})

	tableName := _productTaxRate.productTaxRateDo.TableName()
	_productTaxRate.ALL = field.NewAsterisk(tableName)
	_productTaxRate.ProductID = field.NewString(tableName, "product_id")
	_productTaxRate.RateID = field.NewString(tableName, "rate_id")
	_productTaxRate.CreatedAt = field.NewTime(tableName, "created_at")
	_productTaxRate.UpdatedAt = field.NewTime(tableName, "updated_at")
	_productTaxRate.Metadata = field.NewString(tableName, "metadata")

	_productTaxRate.fillFieldMap()

	return _productTaxRate
}

type productTaxRate struct {
	productTaxRateDo productTaxRateDo

	ALL       field.Asterisk
	ProductID field.String
	RateID    field.String
	CreatedAt field.Time
	UpdatedAt field.Time
	Metadata  field.String

	fieldMap map[string]field.Expr
}

func (p productTaxRate) Table(newTableName string) *productTaxRate {
	p.productTaxRateDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p productTaxRate) As(alias string) *productTaxRate {
	p.productTaxRateDo.DO = *(p.productTaxRateDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *productTaxRate) updateTableName(table string) *productTaxRate {
	p.ALL = field.NewAsterisk(table)
	p.ProductID = field.NewString(table, "product_id")
	p.RateID = field.NewString(table, "rate_id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.Metadata = field.NewString(table, "metadata")

	p.fillFieldMap()

	return p
}

func (p *productTaxRate) WithContext(ctx context.Context) *productTaxRateDo {
	return p.productTaxRateDo.WithContext(ctx)
}

func (p productTaxRate) TableName() string { return p.productTaxRateDo.TableName() }

func (p productTaxRate) Alias() string { return p.productTaxRateDo.Alias() }

func (p productTaxRate) Columns(cols ...field.Expr) gen.Columns {
	return p.productTaxRateDo.Columns(cols...)
}

func (p *productTaxRate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *productTaxRate) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 5)
	p.fieldMap["product_id"] = p.ProductID
	p.fieldMap["rate_id"] = p.RateID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["metadata"] = p.Metadata
}

func (p productTaxRate) clone(db *gorm.DB) productTaxRate {
	p.productTaxRateDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p productTaxRate) replaceDB(db *gorm.DB) productTaxRate {
	p.productTaxRateDo.ReplaceDB(db)
	return p
}

type productTaxRateDo struct{ gen.DO }

func (p productTaxRateDo) Debug() *productTaxRateDo {
	return p.withDO(p.DO.Debug())
}

func (p productTaxRateDo) WithContext(ctx context.Context) *productTaxRateDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p productTaxRateDo) ReadDB() *productTaxRateDo {
	return p.Clauses(dbresolver.Read)
}

func (p productTaxRateDo) WriteDB() *productTaxRateDo {
	return p.Clauses(dbresolver.Write)
}

func (p productTaxRateDo) Session(config *gorm.Session) *productTaxRateDo {
	return p.withDO(p.DO.Session(config))
}

func (p productTaxRateDo) Clauses(conds ...clause.Expression) *productTaxRateDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p productTaxRateDo) Returning(value interface{}, columns ...string) *productTaxRateDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p productTaxRateDo) Not(conds ...gen.Condition) *productTaxRateDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p productTaxRateDo) Or(conds ...gen.Condition) *productTaxRateDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p productTaxRateDo) Select(conds ...field.Expr) *productTaxRateDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p productTaxRateDo) Where(conds ...gen.Condition) *productTaxRateDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p productTaxRateDo) Order(conds ...field.Expr) *productTaxRateDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p productTaxRateDo) Distinct(cols ...field.Expr) *productTaxRateDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p productTaxRateDo) Omit(cols ...field.Expr) *productTaxRateDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p productTaxRateDo) Join(table schema.Tabler, on ...field.Expr) *productTaxRateDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p productTaxRateDo) LeftJoin(table schema.Tabler, on ...field.Expr) *productTaxRateDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p productTaxRateDo) RightJoin(table schema.Tabler, on ...field.Expr) *productTaxRateDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p productTaxRateDo) Group(cols ...field.Expr) *productTaxRateDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p productTaxRateDo) Having(conds ...gen.Condition) *productTaxRateDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p productTaxRateDo) Limit(limit int) *productTaxRateDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p productTaxRateDo) Offset(offset int) *productTaxRateDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p productTaxRateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *productTaxRateDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p productTaxRateDo) Unscoped() *productTaxRateDo {
	return p.withDO(p.DO.Unscoped())
}

func (p productTaxRateDo) Create(values ...*model.ProductTaxRate) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p productTaxRateDo) CreateInBatches(values []*model.ProductTaxRate, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p productTaxRateDo) Save(values ...*model.ProductTaxRate) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p productTaxRateDo) First() (*model.ProductTaxRate, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductTaxRate), nil
	}
}

func (p productTaxRateDo) Take() (*model.ProductTaxRate, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductTaxRate), nil
	}
}

func (p productTaxRateDo) Last() (*model.ProductTaxRate, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductTaxRate), nil
	}
}

func (p productTaxRateDo) Find() ([]*model.ProductTaxRate, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProductTaxRate), err
}

func (p productTaxRateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProductTaxRate, err error) {
	buf := make([]*model.ProductTaxRate, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p productTaxRateDo) FindInBatches(result *[]*model.ProductTaxRate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p productTaxRateDo) Attrs(attrs ...field.AssignExpr) *productTaxRateDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p productTaxRateDo) Assign(attrs ...field.AssignExpr) *productTaxRateDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p productTaxRateDo) Joins(fields ...field.RelationField) *productTaxRateDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p productTaxRateDo) Preload(fields ...field.RelationField) *productTaxRateDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p productTaxRateDo) FirstOrInit() (*model.ProductTaxRate, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductTaxRate), nil
	}
}

func (p productTaxRateDo) FirstOrCreate() (*model.ProductTaxRate, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProductTaxRate), nil
	}
}

func (p productTaxRateDo) FindByPage(offset int, limit int) (result []*model.ProductTaxRate, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p productTaxRateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p productTaxRateDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p productTaxRateDo) Delete(models ...*model.ProductTaxRate) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *productTaxRateDo) withDO(do gen.Dao) *productTaxRateDo {
	p.DO = *do.(*gen.DO)
	return p
}
