// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/driver005/gateway/model"
)

func newPublishableAPIKeySalesChannel(db *gorm.DB, opts ...gen.DOOption) publishableAPIKeySalesChannel {
	_publishableAPIKeySalesChannel := publishableAPIKeySalesChannel{}

	_publishableAPIKeySalesChannel.publishableAPIKeySalesChannelDo.UseDB(db, opts...)
	_publishableAPIKeySalesChannel.publishableAPIKeySalesChannelDo.UseModel(&model.PublishableAPIKeySalesChannel{})

	tableName := _publishableAPIKeySalesChannel.publishableAPIKeySalesChannelDo.TableName()
	_publishableAPIKeySalesChannel.ALL = field.NewAsterisk(tableName)
	_publishableAPIKeySalesChannel.SalesChannelID = field.NewString(tableName, "sales_channel_id")
	_publishableAPIKeySalesChannel.PublishableKeyID = field.NewString(tableName, "publishable_key_id")
	_publishableAPIKeySalesChannel.ID = field.NewString(tableName, "id")
	_publishableAPIKeySalesChannel.CreatedAt = field.NewTime(tableName, "created_at")
	_publishableAPIKeySalesChannel.UpdatedAt = field.NewTime(tableName, "updated_at")
	_publishableAPIKeySalesChannel.DeletedAt = field.NewField(tableName, "deleted_at")

	_publishableAPIKeySalesChannel.fillFieldMap()

	return _publishableAPIKeySalesChannel
}

type publishableAPIKeySalesChannel struct {
	publishableAPIKeySalesChannelDo publishableAPIKeySalesChannelDo

	ALL              field.Asterisk
	SalesChannelID   field.String
	PublishableKeyID field.String
	ID               field.String
	CreatedAt        field.Time
	UpdatedAt        field.Time
	DeletedAt        field.Field

	fieldMap map[string]field.Expr
}

func (p publishableAPIKeySalesChannel) Table(newTableName string) *publishableAPIKeySalesChannel {
	p.publishableAPIKeySalesChannelDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p publishableAPIKeySalesChannel) As(alias string) *publishableAPIKeySalesChannel {
	p.publishableAPIKeySalesChannelDo.DO = *(p.publishableAPIKeySalesChannelDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *publishableAPIKeySalesChannel) updateTableName(table string) *publishableAPIKeySalesChannel {
	p.ALL = field.NewAsterisk(table)
	p.SalesChannelID = field.NewString(table, "sales_channel_id")
	p.PublishableKeyID = field.NewString(table, "publishable_key_id")
	p.ID = field.NewString(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")

	p.fillFieldMap()

	return p
}

func (p *publishableAPIKeySalesChannel) WithContext(ctx context.Context) *publishableAPIKeySalesChannelDo {
	return p.publishableAPIKeySalesChannelDo.WithContext(ctx)
}

func (p publishableAPIKeySalesChannel) TableName() string {
	return p.publishableAPIKeySalesChannelDo.TableName()
}

func (p publishableAPIKeySalesChannel) Alias() string {
	return p.publishableAPIKeySalesChannelDo.Alias()
}

func (p publishableAPIKeySalesChannel) Columns(cols ...field.Expr) gen.Columns {
	return p.publishableAPIKeySalesChannelDo.Columns(cols...)
}

func (p *publishableAPIKeySalesChannel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *publishableAPIKeySalesChannel) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 6)
	p.fieldMap["sales_channel_id"] = p.SalesChannelID
	p.fieldMap["publishable_key_id"] = p.PublishableKeyID
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
}

func (p publishableAPIKeySalesChannel) clone(db *gorm.DB) publishableAPIKeySalesChannel {
	p.publishableAPIKeySalesChannelDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p publishableAPIKeySalesChannel) replaceDB(db *gorm.DB) publishableAPIKeySalesChannel {
	p.publishableAPIKeySalesChannelDo.ReplaceDB(db)
	return p
}

type publishableAPIKeySalesChannelDo struct{ gen.DO }

func (p publishableAPIKeySalesChannelDo) Debug() *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.Debug())
}

func (p publishableAPIKeySalesChannelDo) WithContext(ctx context.Context) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p publishableAPIKeySalesChannelDo) ReadDB() *publishableAPIKeySalesChannelDo {
	return p.Clauses(dbresolver.Read)
}

func (p publishableAPIKeySalesChannelDo) WriteDB() *publishableAPIKeySalesChannelDo {
	return p.Clauses(dbresolver.Write)
}

func (p publishableAPIKeySalesChannelDo) Session(config *gorm.Session) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.Session(config))
}

func (p publishableAPIKeySalesChannelDo) Clauses(conds ...clause.Expression) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p publishableAPIKeySalesChannelDo) Returning(value interface{}, columns ...string) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p publishableAPIKeySalesChannelDo) Not(conds ...gen.Condition) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p publishableAPIKeySalesChannelDo) Or(conds ...gen.Condition) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p publishableAPIKeySalesChannelDo) Select(conds ...field.Expr) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p publishableAPIKeySalesChannelDo) Where(conds ...gen.Condition) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p publishableAPIKeySalesChannelDo) Order(conds ...field.Expr) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p publishableAPIKeySalesChannelDo) Distinct(cols ...field.Expr) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p publishableAPIKeySalesChannelDo) Omit(cols ...field.Expr) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p publishableAPIKeySalesChannelDo) Join(table schema.Tabler, on ...field.Expr) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p publishableAPIKeySalesChannelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p publishableAPIKeySalesChannelDo) RightJoin(table schema.Tabler, on ...field.Expr) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p publishableAPIKeySalesChannelDo) Group(cols ...field.Expr) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p publishableAPIKeySalesChannelDo) Having(conds ...gen.Condition) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p publishableAPIKeySalesChannelDo) Limit(limit int) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p publishableAPIKeySalesChannelDo) Offset(offset int) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p publishableAPIKeySalesChannelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p publishableAPIKeySalesChannelDo) Unscoped() *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.Unscoped())
}

func (p publishableAPIKeySalesChannelDo) Create(values ...*model.PublishableAPIKeySalesChannel) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p publishableAPIKeySalesChannelDo) CreateInBatches(values []*model.PublishableAPIKeySalesChannel, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p publishableAPIKeySalesChannelDo) Save(values ...*model.PublishableAPIKeySalesChannel) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p publishableAPIKeySalesChannelDo) First() (*model.PublishableAPIKeySalesChannel, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PublishableAPIKeySalesChannel), nil
	}
}

func (p publishableAPIKeySalesChannelDo) Take() (*model.PublishableAPIKeySalesChannel, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PublishableAPIKeySalesChannel), nil
	}
}

func (p publishableAPIKeySalesChannelDo) Last() (*model.PublishableAPIKeySalesChannel, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PublishableAPIKeySalesChannel), nil
	}
}

func (p publishableAPIKeySalesChannelDo) Find() ([]*model.PublishableAPIKeySalesChannel, error) {
	result, err := p.DO.Find()
	return result.([]*model.PublishableAPIKeySalesChannel), err
}

func (p publishableAPIKeySalesChannelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PublishableAPIKeySalesChannel, err error) {
	buf := make([]*model.PublishableAPIKeySalesChannel, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p publishableAPIKeySalesChannelDo) FindInBatches(result *[]*model.PublishableAPIKeySalesChannel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p publishableAPIKeySalesChannelDo) Attrs(attrs ...field.AssignExpr) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p publishableAPIKeySalesChannelDo) Assign(attrs ...field.AssignExpr) *publishableAPIKeySalesChannelDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p publishableAPIKeySalesChannelDo) Joins(fields ...field.RelationField) *publishableAPIKeySalesChannelDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p publishableAPIKeySalesChannelDo) Preload(fields ...field.RelationField) *publishableAPIKeySalesChannelDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p publishableAPIKeySalesChannelDo) FirstOrInit() (*model.PublishableAPIKeySalesChannel, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PublishableAPIKeySalesChannel), nil
	}
}

func (p publishableAPIKeySalesChannelDo) FirstOrCreate() (*model.PublishableAPIKeySalesChannel, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PublishableAPIKeySalesChannel), nil
	}
}

func (p publishableAPIKeySalesChannelDo) FindByPage(offset int, limit int) (result []*model.PublishableAPIKeySalesChannel, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p publishableAPIKeySalesChannelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p publishableAPIKeySalesChannelDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p publishableAPIKeySalesChannelDo) Delete(models ...*model.PublishableAPIKeySalesChannel) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *publishableAPIKeySalesChannelDo) withDO(do gen.Dao) *publishableAPIKeySalesChannelDo {
	p.DO = *do.(*gen.DO)
	return p
}
