// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/driver005/gateway/model"
)

func newShippingOptionType(db *gorm.DB, opts ...gen.DOOption) shippingOptionType {
	_shippingOptionType := shippingOptionType{}

	_shippingOptionType.shippingOptionTypeDo.UseDB(db, opts...)
	_shippingOptionType.shippingOptionTypeDo.UseModel(&model.ShippingOptionType{})

	tableName := _shippingOptionType.shippingOptionTypeDo.TableName()
	_shippingOptionType.ALL = field.NewAsterisk(tableName)
	_shippingOptionType.ID = field.NewString(tableName, "id")
	_shippingOptionType.Label = field.NewString(tableName, "label")
	_shippingOptionType.Description = field.NewString(tableName, "description")
	_shippingOptionType.Code = field.NewString(tableName, "code")
	_shippingOptionType.ShippingOptionID = field.NewString(tableName, "shipping_option_id")
	_shippingOptionType.CreatedAt = field.NewTime(tableName, "created_at")
	_shippingOptionType.UpdatedAt = field.NewTime(tableName, "updated_at")
	_shippingOptionType.DeletedAt = field.NewField(tableName, "deleted_at")

	_shippingOptionType.fillFieldMap()

	return _shippingOptionType
}

type shippingOptionType struct {
	shippingOptionTypeDo shippingOptionTypeDo

	ALL              field.Asterisk
	ID               field.String
	Label            field.String
	Description      field.String
	Code             field.String
	ShippingOptionID field.String
	CreatedAt        field.Time
	UpdatedAt        field.Time
	DeletedAt        field.Field

	fieldMap map[string]field.Expr
}

func (s shippingOptionType) Table(newTableName string) *shippingOptionType {
	s.shippingOptionTypeDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s shippingOptionType) As(alias string) *shippingOptionType {
	s.shippingOptionTypeDo.DO = *(s.shippingOptionTypeDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *shippingOptionType) updateTableName(table string) *shippingOptionType {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewString(table, "id")
	s.Label = field.NewString(table, "label")
	s.Description = field.NewString(table, "description")
	s.Code = field.NewString(table, "code")
	s.ShippingOptionID = field.NewString(table, "shipping_option_id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *shippingOptionType) WithContext(ctx context.Context) *shippingOptionTypeDo {
	return s.shippingOptionTypeDo.WithContext(ctx)
}

func (s shippingOptionType) TableName() string { return s.shippingOptionTypeDo.TableName() }

func (s shippingOptionType) Alias() string { return s.shippingOptionTypeDo.Alias() }

func (s shippingOptionType) Columns(cols ...field.Expr) gen.Columns {
	return s.shippingOptionTypeDo.Columns(cols...)
}

func (s *shippingOptionType) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *shippingOptionType) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 8)
	s.fieldMap["id"] = s.ID
	s.fieldMap["label"] = s.Label
	s.fieldMap["description"] = s.Description
	s.fieldMap["code"] = s.Code
	s.fieldMap["shipping_option_id"] = s.ShippingOptionID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s shippingOptionType) clone(db *gorm.DB) shippingOptionType {
	s.shippingOptionTypeDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s shippingOptionType) replaceDB(db *gorm.DB) shippingOptionType {
	s.shippingOptionTypeDo.ReplaceDB(db)
	return s
}

type shippingOptionTypeDo struct{ gen.DO }

func (s shippingOptionTypeDo) Debug() *shippingOptionTypeDo {
	return s.withDO(s.DO.Debug())
}

func (s shippingOptionTypeDo) WithContext(ctx context.Context) *shippingOptionTypeDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s shippingOptionTypeDo) ReadDB() *shippingOptionTypeDo {
	return s.Clauses(dbresolver.Read)
}

func (s shippingOptionTypeDo) WriteDB() *shippingOptionTypeDo {
	return s.Clauses(dbresolver.Write)
}

func (s shippingOptionTypeDo) Session(config *gorm.Session) *shippingOptionTypeDo {
	return s.withDO(s.DO.Session(config))
}

func (s shippingOptionTypeDo) Clauses(conds ...clause.Expression) *shippingOptionTypeDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s shippingOptionTypeDo) Returning(value interface{}, columns ...string) *shippingOptionTypeDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s shippingOptionTypeDo) Not(conds ...gen.Condition) *shippingOptionTypeDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s shippingOptionTypeDo) Or(conds ...gen.Condition) *shippingOptionTypeDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s shippingOptionTypeDo) Select(conds ...field.Expr) *shippingOptionTypeDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s shippingOptionTypeDo) Where(conds ...gen.Condition) *shippingOptionTypeDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s shippingOptionTypeDo) Order(conds ...field.Expr) *shippingOptionTypeDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s shippingOptionTypeDo) Distinct(cols ...field.Expr) *shippingOptionTypeDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s shippingOptionTypeDo) Omit(cols ...field.Expr) *shippingOptionTypeDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s shippingOptionTypeDo) Join(table schema.Tabler, on ...field.Expr) *shippingOptionTypeDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s shippingOptionTypeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *shippingOptionTypeDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s shippingOptionTypeDo) RightJoin(table schema.Tabler, on ...field.Expr) *shippingOptionTypeDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s shippingOptionTypeDo) Group(cols ...field.Expr) *shippingOptionTypeDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s shippingOptionTypeDo) Having(conds ...gen.Condition) *shippingOptionTypeDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s shippingOptionTypeDo) Limit(limit int) *shippingOptionTypeDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s shippingOptionTypeDo) Offset(offset int) *shippingOptionTypeDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s shippingOptionTypeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *shippingOptionTypeDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s shippingOptionTypeDo) Unscoped() *shippingOptionTypeDo {
	return s.withDO(s.DO.Unscoped())
}

func (s shippingOptionTypeDo) Create(values ...*model.ShippingOptionType) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s shippingOptionTypeDo) CreateInBatches(values []*model.ShippingOptionType, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s shippingOptionTypeDo) Save(values ...*model.ShippingOptionType) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s shippingOptionTypeDo) First() (*model.ShippingOptionType, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShippingOptionType), nil
	}
}

func (s shippingOptionTypeDo) Take() (*model.ShippingOptionType, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShippingOptionType), nil
	}
}

func (s shippingOptionTypeDo) Last() (*model.ShippingOptionType, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShippingOptionType), nil
	}
}

func (s shippingOptionTypeDo) Find() ([]*model.ShippingOptionType, error) {
	result, err := s.DO.Find()
	return result.([]*model.ShippingOptionType), err
}

func (s shippingOptionTypeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ShippingOptionType, err error) {
	buf := make([]*model.ShippingOptionType, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s shippingOptionTypeDo) FindInBatches(result *[]*model.ShippingOptionType, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s shippingOptionTypeDo) Attrs(attrs ...field.AssignExpr) *shippingOptionTypeDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s shippingOptionTypeDo) Assign(attrs ...field.AssignExpr) *shippingOptionTypeDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s shippingOptionTypeDo) Joins(fields ...field.RelationField) *shippingOptionTypeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s shippingOptionTypeDo) Preload(fields ...field.RelationField) *shippingOptionTypeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s shippingOptionTypeDo) FirstOrInit() (*model.ShippingOptionType, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShippingOptionType), nil
	}
}

func (s shippingOptionTypeDo) FirstOrCreate() (*model.ShippingOptionType, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ShippingOptionType), nil
	}
}

func (s shippingOptionTypeDo) FindByPage(offset int, limit int) (result []*model.ShippingOptionType, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s shippingOptionTypeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s shippingOptionTypeDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s shippingOptionTypeDo) Delete(models ...*model.ShippingOptionType) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *shippingOptionTypeDo) withDO(do gen.Dao) *shippingOptionTypeDo {
	s.DO = *do.(*gen.DO)
	return s
}
