package utils

type Currency struct {
	Symbol        string
	Name          string
	SymbolNative  string
	DecimalDigits int
	Rounding      float64
	Code          string
	NamePlural    string
}

var Currencies = map[string]Currency{
	"USD": {
		Symbol:        "$",
		Name:          "US Dollar",
		SymbolNative:  "$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "USD",
		NamePlural:    "US dollars",
	},
	"CAD": {
		Symbol:        "CA$",
		Name:          "Canadian Dollar",
		SymbolNative:  "$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "CAD",
		NamePlural:    "Canadian dollars",
	},
	"EUR": {
		Symbol:        "€",
		Name:          "Euro",
		SymbolNative:  "€",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "EUR",
		NamePlural:    "euros",
	},
	"AED": {
		Symbol:        "AED",
		Name:          "United Arab Emirates Dirham",
		SymbolNative:  "د.إ.‏",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "AED",
		NamePlural:    "UAE dirhams",
	},
	"AFN": {
		Symbol:        "Af",
		Name:          "Afghan Afghani",
		SymbolNative:  "؋",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "AFN",
		NamePlural:    "Afghan Afghanis",
	},
	"ALL": {
		Symbol:        "ALL",
		Name:          "Albanian Lek",
		SymbolNative:  "Lek",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "ALL",
		NamePlural:    "Albanian lekë",
	},
	"AMD": {
		Symbol:        "AMD",
		Name:          "Armenian Dram",
		SymbolNative:  "դր.",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "AMD",
		NamePlural:    "Armenian drams",
	},
	"ARS": {
		Symbol:        "AR$",
		Name:          "Argentine Peso",
		SymbolNative:  "$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "ARS",
		NamePlural:    "Argentine pesos",
	},
	"AUD": {
		Symbol:        "AU$",
		Name:          "Australian Dollar",
		SymbolNative:  "$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "AUD",
		NamePlural:    "Australian dollars",
	},
	"AZN": {
		Symbol:        "man.",
		Name:          "Azerbaijani Manat",
		SymbolNative:  "ман.",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "AZN",
		NamePlural:    "Azerbaijani manats",
	},
	"BAM": {
		Symbol:        "KM",
		Name:          "Bosnia-Herzegovina Convertible Mark",
		SymbolNative:  "KM",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "BAM",
		NamePlural:    "Bosnia-Herzegovina convertible marks",
	},
	"BDT": {
		Symbol:        "Tk",
		Name:          "Bangladeshi Taka",
		SymbolNative:  "৳",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "BDT",
		NamePlural:    "Bangladeshi takas",
	},
	"BGN": {
		Symbol:        "BGN",
		Name:          "Bulgarian Lev",
		SymbolNative:  "лв.",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "BGN",
		NamePlural:    "Bulgarian leva",
	},
	"BHD": {
		Symbol:        "BD",
		Name:          "Bahraini Dinar",
		SymbolNative:  "د.ب.‏",
		DecimalDigits: 3,
		Rounding:      0,
		Code:          "BHD",
		NamePlural:    "Bahraini dinars",
	},
	"BIF": {
		Symbol:        "FBu",
		Name:          "Burundian Franc",
		SymbolNative:  "FBu",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "BIF",
		NamePlural:    "Burundian francs",
	},
	"BND": {
		Symbol:        "BN$",
		Name:          "Brunei Dollar",
		SymbolNative:  "$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "BND",
		NamePlural:    "Brunei dollars",
	},
	"BOB": {
		Symbol:        "Bs",
		Name:          "Bolivian Boliviano",
		SymbolNative:  "Bs",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "BOB",
		NamePlural:    "Bolivian bolivianos",
	},
	"BRL": {
		Symbol:        "R$",
		Name:          "Brazilian Real",
		SymbolNative:  "R$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "BRL",
		NamePlural:    "Brazilian reals",
	},
	"BWP": {
		Symbol:        "BWP",
		Name:          "Botswanan Pula",
		SymbolNative:  "P",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "BWP",
		NamePlural:    "Botswanan pulas",
	},
	"BYN": {
		Symbol:        "Br",
		Name:          "Belarusian Ruble",
		SymbolNative:  "руб.",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "BYN",
		NamePlural:    "Belarusian rubles",
	},
	"BZD": {
		Symbol:        "BZ$",
		Name:          "Belize Dollar",
		SymbolNative:  "$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "BZD",
		NamePlural:    "Belize dollars",
	},
	"CDF": {
		Symbol:        "CDF",
		Name:          "Congolese Franc",
		SymbolNative:  "FrCD",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "CDF",
		NamePlural:    "Congolese francs",
	},
	"CHF": {
		Symbol:        "CHF",
		Name:          "Swiss Franc",
		SymbolNative:  "CHF",
		DecimalDigits: 2,
		Rounding:      0.05,
		Code:          "CHF",
		NamePlural:    "Swiss francs",
	},
	"CLP": {
		Symbol:        "CL$",
		Name:          "Chilean Peso",
		SymbolNative:  "$",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "CLP",
		NamePlural:    "Chilean pesos",
	},
	"CNY": {
		Symbol:        "CN¥",
		Name:          "Chinese Yuan",
		SymbolNative:  "CN¥",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "CNY",
		NamePlural:    "Chinese yuan",
	},
	"COP": {
		Symbol:        "CO$",
		Name:          "Colombian Peso",
		SymbolNative:  "$",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "COP",
		NamePlural:    "Colombian pesos",
	},
	"CRC": {
		Symbol:        "₡",
		Name:          "Costa Rican Colón",
		SymbolNative:  "₡",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "CRC",
		NamePlural:    "Costa Rican colóns",
	},
	"CVE": {
		Symbol:        "CV$",
		Name:          "Cape Verdean Escudo",
		SymbolNative:  "CV$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "CVE",
		NamePlural:    "Cape Verdean escudos",
	},
	"CZK": {
		Symbol:        "Kč",
		Name:          "Czech Republic Koruna",
		SymbolNative:  "Kč",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "CZK",
		NamePlural:    "Czech Republic korunas",
	},
	"DJF": {
		Symbol:        "Fdj",
		Name:          "Djiboutian Franc",
		SymbolNative:  "Fdj",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "DJF",
		NamePlural:    "Djiboutian francs",
	},
	"DKK": {
		Symbol:        "Dkr",
		Name:          "Danish Krone",
		SymbolNative:  "kr",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "DKK",
		NamePlural:    "Danish kroner",
	},
	"DOP": {
		Symbol:        "RD$",
		Name:          "Dominican Peso",
		SymbolNative:  "RD$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "DOP",
		NamePlural:    "Dominican pesos",
	},
	"DZD": {
		Symbol:        "DA",
		Name:          "Algerian Dinar",
		SymbolNative:  "د.��.‏",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "DZD",
		NamePlural:    "Algerian dinars",
	},
	"EEK": {
		Symbol:        "Ekr",
		Name:          "Estonian Kroon",
		SymbolNative:  "kr",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "EEK",
		NamePlural:    "Estonian kroons",
	},
	"EGP": {
		Symbol:        "EGP",
		Name:          "Egyptian Pound",
		SymbolNative:  "ج.م.‏",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "EGP",
		NamePlural:    "Egyptian pounds",
	},
	"ERN": {
		Symbol:        "Nfk",
		Name:          "Eritrean Nakfa",
		SymbolNative:  "Nfk",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "ERN",
		NamePlural:    "Eritrean nakfas",
	},
	"ETB": {
		Symbol:        "Br",
		Name:          "Ethiopian Birr",
		SymbolNative:  "Br",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "ETB",
		NamePlural:    "Ethiopian birrs",
	},
	"GBP": {
		Symbol:        "£",
		Name:          "British Pound Sterling",
		SymbolNative:  "£",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "GBP",
		NamePlural:    "British pounds sterling",
	},
	"GEL": {
		Symbol:        "GEL",
		Name:          "Georgian Lari",
		SymbolNative:  "GEL",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "GEL",
		NamePlural:    "Georgian laris",
	},
	"GHS": {
		Symbol:        "GH₵",
		Name:          "Ghanaian Cedi",
		SymbolNative:  "GH₵",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "GHS",
		NamePlural:    "Ghanaian cedis",
	},
	"GNF": {
		Symbol:        "FG",
		Name:          "Guinean Franc",
		SymbolNative:  "FG",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "GNF",
		NamePlural:    "Guinean francs",
	},
	"GTQ": {
		Symbol:        "GTQ",
		Name:          "Guatemalan Quetzal",
		SymbolNative:  "Q",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "GTQ",
		NamePlural:    "Guatemalan quetzals",
	},
	"HKD": {
		Symbol:        "HK$",
		Name:          "Hong Kong Dollar",
		SymbolNative:  "$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "HKD",
		NamePlural:    "Hong Kong dollars",
	},
	"HNL": {
		Symbol:        "HNL",
		Name:          "Honduran Lempira",
		SymbolNative:  "L",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "HNL",
		NamePlural:    "Honduran lempiras",
	},
	"HRK": {
		Symbol:        "kn",
		Name:          "Croatian Kuna",
		SymbolNative:  "kn",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "HRK",
		NamePlural:    "Croatian kunas",
	},
	"HUF": {
		Symbol:        "Ft",
		Name:          "Hungarian Forint",
		SymbolNative:  "Ft",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "HUF",
		NamePlural:    "Hungarian forints",
	},
	"IDR": {
		Symbol:        "Rp",
		Name:          "Indonesian Rupiah",
		SymbolNative:  "Rp",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "IDR",
		NamePlural:    "Indonesian rupiahs",
	},
	"ILS": {
		Symbol:        "₪",
		Name:          "Israeli New Sheqel",
		SymbolNative:  "₪",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "ILS",
		NamePlural:    "Israeli new sheqels",
	},
	"INR": {
		Symbol:        "Rs",
		Name:          "Indian Rupee",
		SymbolNative:  "টকা",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "INR",
		NamePlural:    "Indian rupees",
	},
	"IQD": {
		Symbol:        "IQD",
		Name:          "Iraqi Dinar",
		SymbolNative:  "د.ع.‏",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "IQD",
		NamePlural:    "Iraqi dinars",
	},
	"IRR": {
		Symbol:        "IRR",
		Name:          "Iranian Rial",
		SymbolNative:  "��",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "IRR",
		NamePlural:    "Iranian rials",
	},
	"ISK": {
		Symbol:        "Ikr",
		Name:          "Icelandic Króna",
		SymbolNative:  "kr",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "ISK",
		NamePlural:    "Icelandic krónur",
	},
	"JMD": {
		Symbol:        "J$",
		Name:          "Jamaican Dollar",
		SymbolNative:  "$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "JMD",
		NamePlural:    "Jamaican dollars",
	},
	"JOD": {
		Symbol:        "JD",
		Name:          "Jordanian Dinar",
		SymbolNative:  "د.أ.‏",
		DecimalDigits: 3,
		Rounding:      0,
		Code:          "JOD",
		NamePlural:    "Jordanian dinars",
	},
	"JPY": {
		Symbol:        "¥",
		Name:          "Japanese Yen",
		SymbolNative:  "￥",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "JPY",
		NamePlural:    "Japanese yen",
	},
	"KES": {
		Symbol:        "Ksh",
		Name:          "Kenyan Shilling",
		SymbolNative:  "Ksh",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "KES",
		NamePlural:    "Kenyan shillings",
	},
	"KHR": {
		Symbol:        "KHR",
		Name:          "Cambodian Riel",
		SymbolNative:  "៛",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "KHR",
		NamePlural:    "Cambodian riels",
	},
	"KMF": {
		Symbol:        "CF",
		Name:          "Comorian Franc",
		SymbolNative:  "FC",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "KMF",
		NamePlural:    "Comorian francs",
	},
	"KRW": {
		Symbol:        "₩",
		Name:          "South Korean Won",
		SymbolNative:  "₩",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "KRW",
		NamePlural:    "South Korean won",
	},
	"KWD": {
		Symbol:        "KD",
		Name:          "Kuwaiti Dinar",
		SymbolNative:  "د.ك.‏",
		DecimalDigits: 3,
		Rounding:      0,
		Code:          "KWD",
		NamePlural:    "Kuwaiti dinars",
	},
	"KZT": {
		Symbol:        "KZT",
		Name:          "Kazakhstani Tenge",
		SymbolNative:  "тңг.",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "KZT",
		NamePlural:    "Kazakhstani tenges",
	},
	"LBP": {
		Symbol:        "LB£",
		Name:          "Lebanese Pound",
		SymbolNative:  "ل.ل.‏",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "LBP",
		NamePlural:    "Lebanese pounds",
	},
	"LKR": {
		Symbol:        "SLRs",
		Name:          "Sri Lankan Rupee",
		SymbolNative:  "SL Re",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "LKR",
		NamePlural:    "Sri Lankan rupees",
	},
	"LTL": {
		Symbol:        "Lt",
		Name:          "Lithuanian Litas",
		SymbolNative:  "Lt",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "LTL",
		NamePlural:    "Lithuanian litai",
	},
	"LVL": {
		Symbol:        "Ls",
		Name:          "Latvian Lats",
		SymbolNative:  "Ls",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "LVL",
		NamePlural:    "Latvian lati",
	},
	"LYD": {
		Symbol:        "LD",
		Name:          "Libyan Dinar",
		SymbolNative:  "د.ل.‏",
		DecimalDigits: 3,
		Rounding:      0,
		Code:          "LYD",
		NamePlural:    "Libyan dinars",
	},
	"MAD": {
		Symbol:        "MAD",
		Name:          "Moroccan Dirham",
		SymbolNative:  "د.م.‏",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "MAD",
		NamePlural:    "Moroccan dirhams",
	},
	"MDL": {
		Symbol:        "MDL",
		Name:          "Moldovan Leu",
		SymbolNative:  "MDL",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "MDL",
		NamePlural:    "Moldovan lei",
	},
	"MGA": {
		Symbol:        "MGA",
		Name:          "Malagasy Ariary",
		SymbolNative:  "MGA",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "MGA",
		NamePlural:    "Malagasy Ariaries",
	},
	"MKD": {
		Symbol:        "MKD",
		Name:          "Macedonian Denar",
		SymbolNative:  "MKD",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "MKD",
		NamePlural:    "Macedonian denari",
	},
	"MMK": {
		Symbol:        "MMK",
		Name:          "Myanma Kyat",
		SymbolNative:  "K",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "MMK",
		NamePlural:    "Myanma kyats",
	},
	"MNT": {
		Symbol:        "MNT",
		Name:          "Mongolian Tugrig",
		SymbolNative:  "₮",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "MNT",
		NamePlural:    "Mongolian Tugrugs",
	},
	"MOP": {
		Symbol:        "MOP$",
		Name:          "Macanese Pataca",
		SymbolNative:  "MOP$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "MOP",
		NamePlural:    "Macanese patacas",
	},
	"MUR": {
		Symbol:        "MURs",
		Name:          "Mauritian Rupee",
		SymbolNative:  "MURs",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "MUR",
		NamePlural:    "Mauritian rupees",
	},
	"MXN": {
		Symbol:        "MX$",
		Name:          "Mexican Peso",
		SymbolNative:  "$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "MXN",
		NamePlural:    "Mexican pesos",
	},
	"MYR": {
		Symbol:        "RM",
		Name:          "Malaysian Ringgit",
		SymbolNative:  "RM",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "MYR",
		NamePlural:    "Malaysian ringgits",
	},
	"MZN": {
		Symbol:        "MTn",
		Name:          "Mozambican Metical",
		SymbolNative:  "MTn",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "MZN",
		NamePlural:    "Mozambican meticals",
	},
	"NAD": {
		Symbol:        "N$",
		Name:          "Namibian Dollar",
		SymbolNative:  "N$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "NAD",
		NamePlural:    "Namibian dollars",
	},
	"NGN": {
		Symbol:        "₦",
		Name:          "Nigerian Naira",
		SymbolNative:  "₦",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "NGN",
		NamePlural:    "Nigerian nairas",
	},
	"NIO": {
		Symbol:        "C$",
		Name:          "Nicaraguan Córdoba",
		SymbolNative:  "C$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "NIO",
		NamePlural:    "Nicaraguan córdobas",
	},
	"NOK": {
		Symbol:        "Nkr",
		Name:          "Norwegian Krone",
		SymbolNative:  "kr",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "NOK",
		NamePlural:    "Norwegian kroner",
	},
	"NPR": {
		Symbol:        "NPRs",
		Name:          "Nepalese Rupee",
		SymbolNative:  "नेरू",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "NPR",
		NamePlural:    "Nepalese rupees",
	},
	"NZD": {
		Symbol:        "NZ$",
		Name:          "New Zealand Dollar",
		SymbolNative:  "$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "NZD",
		NamePlural:    "New Zealand dollars",
	},
	"OMR": {
		Symbol:        "OMR",
		Name:          "Omani Rial",
		SymbolNative:  "ر.��.‏",
		DecimalDigits: 3,
		Rounding:      0,
		Code:          "OMR",
		NamePlural:    "Omani rials",
	},
	"PAB": {
		Symbol:        "B/.",
		Name:          "Panamanian Balboa",
		SymbolNative:  "B/.",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "PAB",
		NamePlural:    "Panamanian balboas",
	},
	"PEN": {
		Symbol:        "S/.",
		Name:          "Peruvian Nuevo Sol",
		SymbolNative:  "S/.",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "PEN",
		NamePlural:    "Peruvian nuevos soles",
	},
	"PHP": {
		Symbol:        "₱",
		Name:          "Philippine Peso",
		SymbolNative:  "₱",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "PHP",
		NamePlural:    "Philippine pesos",
	},
	"PKR": {
		Symbol:        "PKRs",
		Name:          "Pakistani Rupee",
		SymbolNative:  "��",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "PKR",
		NamePlural:    "Pakistani rupees",
	},
	"PLN": {
		Symbol:        "zł",
		Name:          "Polish Zloty",
		SymbolNative:  "z��",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "PLN",
		NamePlural:    "Polish zlotys",
	},
	"PYG": {
		Symbol:        "₲",
		Name:          "Paraguayan Guarani",
		SymbolNative:  "₲",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "PYG",
		NamePlural:    "Paraguayan guaranis",
	},
	"QAR": {
		Symbol:        "QR",
		Name:          "Qatari Rial",
		SymbolNative:  "ر.ق.‏",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "QAR",
		NamePlural:    "Qatari rials",
	},
	"RON": {
		Symbol:        "RON",
		Name:          "Romanian Leu",
		SymbolNative:  "RON",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "RON",
		NamePlural:    "Romanian lei",
	},
	"RSD": {
		Symbol:        "din.",
		Name:          "Serbian Dinar",
		SymbolNative:  "дин.",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "RSD",
		NamePlural:    "Serbian dinars",
	},
	"RUB": {
		Symbol:        "RUB",
		Name:          "Russian Ruble",
		SymbolNative:  "��.",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "RUB",
		NamePlural:    "Russian rubles",
	},
	"RWF": {
		Symbol:        "RWF",
		Name:          "Rwandan Franc",
		SymbolNative:  "FR",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "RWF",
		NamePlural:    "Rwandan francs",
	},
	"SAR": {
		Symbol:        "SR",
		Name:          "Saudi Riyal",
		SymbolNative:  "ر.س.‏",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "SAR",
		NamePlural:    "Saudi riyals",
	},
	"SDG": {
		Symbol:        "SDG",
		Name:          "Sudanese Pound",
		SymbolNative:  "SDG",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "SDG",
		NamePlural:    "Sudanese pounds",
	},
	"SEK": {
		Symbol:        "Skr",
		Name:          "Swedish Krona",
		SymbolNative:  "kr",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "SEK",
		NamePlural:    "Swedish kronor",
	},
	"SGD": {
		Symbol:        "S$",
		Name:          "Singapore Dollar",
		SymbolNative:  "$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "SGD",
		NamePlural:    "Singapore dollars",
	},
	"SOS": {
		Symbol:        "Ssh",
		Name:          "Somali Shilling",
		SymbolNative:  "Ssh",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "SOS",
		NamePlural:    "Somali shillings",
	},
	"SYP": {
		Symbol:        "SY£",
		Name:          "Syrian Pound",
		SymbolNative:  "ل.س.‏",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "SYP",
		NamePlural:    "Syrian pounds",
	},
	"THB": {
		Symbol:        "฿",
		Name:          "Thai Baht",
		SymbolNative:  "฿",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "THB",
		NamePlural:    "Thai baht",
	},
	"TND": {
		Symbol:        "DT",
		Name:          "Tunisian Dinar",
		SymbolNative:  "د.��.‏",
		DecimalDigits: 3,
		Rounding:      0,
		Code:          "TND",
		NamePlural:    "Tunisian dinars",
	},
	"TOP": {
		Symbol:        "T$",
		Name:          "Tongan Paʻanga",
		SymbolNative:  "T$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "TOP",
		NamePlural:    "Tongan paʻanga",
	},
	"TRY": {
		Symbol:        "TL",
		Name:          "Turkish Lira",
		SymbolNative:  "TL",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "TRY",
		NamePlural:    "Turkish Lira",
	},
	"TTD": {
		Symbol:        "TT$",
		Name:          "Trinidad and Tobago Dollar",
		SymbolNative:  "$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "TTD",
		NamePlural:    "Trinidad and Tobago dollars",
	},
	"TWD": {
		Symbol:        "NT$",
		Name:          "New Taiwan Dollar",
		SymbolNative:  "NT$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "TWD",
		NamePlural:    "New Taiwan dollars",
	},
	"TZS": {
		Symbol:        "TSh",
		Name:          "Tanzanian Shilling",
		SymbolNative:  "TSh",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "TZS",
		NamePlural:    "Tanzanian shillings",
	},
	"UAH": {
		Symbol:        "₴",
		Name:          "Ukrainian Hryvnia",
		SymbolNative:  "₴",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "UAH",
		NamePlural:    "Ukrainian hryvnias",
	},
	"UGX": {
		Symbol:        "USh",
		Name:          "Ugandan Shilling",
		SymbolNative:  "USh",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "UGX",
		NamePlural:    "Ugandan shillings",
	},
	"UYU": {
		Symbol:        "$U",
		Name:          "Uruguayan Peso",
		SymbolNative:  "$",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "UYU",
		NamePlural:    "Uruguayan pesos",
	},
	"UZS": {
		Symbol:        "UZS",
		Name:          "Uzbekistan Som",
		SymbolNative:  "UZS",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "UZS",
		NamePlural:    "Uzbekistan som",
	},
	"VEF": {
		Symbol:        "Bs.F.",
		Name:          "Venezuelan Bolívar",
		SymbolNative:  "Bs.F.",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "VEF",
		NamePlural:    "Venezuelan bolívars",
	},
	"VND": {
		Symbol:        "₫",
		Name:          "Vietnamese Dong",
		SymbolNative:  "₫",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "VND",
		NamePlural:    "Vietnamese dong",
	},
	"XAF": {
		Symbol:        "FCFA",
		Name:          "CFA Franc BEAC",
		SymbolNative:  "FCFA",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "XAF",
		NamePlural:    "CFA francs BEAC",
	},
	"XOF": {
		Symbol:        "CFA",
		Name:          "CFA Franc BCEAO",
		SymbolNative:  "CFA",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "XOF",
		NamePlural:    "CFA francs BCEAO",
	},
	"YER": {
		Symbol:        "YR",
		Name:          "Yemeni Rial",
		SymbolNative:  "ر.ي.‏",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "YER",
		NamePlural:    "Yemeni rials",
	},
	"ZAR": {
		Symbol:        "R",
		Name:          "South African Rand",
		SymbolNative:  "R",
		DecimalDigits: 2,
		Rounding:      0,
		Code:          "ZAR",
		NamePlural:    "South African rand",
	},
	"ZMK": {
		Symbol:        "ZK",
		Name:          "Zambian Kwacha",
		SymbolNative:  "ZK",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "ZMK",
		NamePlural:    "Zambian kwachas",
	},
	"ZWL": {
		Symbol:        "ZWL$",
		Name:          "Zimbabwean Dollar",
		SymbolNative:  "ZWL$",
		DecimalDigits: 0,
		Rounding:      0,
		Code:          "ZWL",
		NamePlural:    "Zimbabwean Dollar",
	},
}
