// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleAPIToken handles api_token security.
	HandleAPIToken(ctx context.Context, operationName string, t APIToken) (context.Context, error)
	// HandleCookieAuth handles cookie_auth security.
	HandleCookieAuth(ctx context.Context, operationName string, t CookieAuth) (context.Context, error)
	// HandleJwtToken handles jwt_token security.
	HandleJwtToken(ctx context.Context, operationName string, t JwtToken) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

func (s *Server) securityAPIToken(ctx context.Context, operationName string, req *http.Request) (context.Context, bool, error) {
	var t APIToken
	const parameterName = "x-medusa-access-token"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	rctx, err := s.sec.HandleAPIToken(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}
func (s *Server) securityCookieAuth(ctx context.Context, operationName string, req *http.Request) (context.Context, bool, error) {
	var t CookieAuth
	const parameterName = "connect.sid"
	var value string
	switch cookie, err := req.Cookie(parameterName); {
	case err == nil: // if NO error
		value = cookie.Value
	case errors.Is(err, http.ErrNoCookie):
		return ctx, false, nil
	default:
		return nil, false, errors.Wrap(err, "get cookie value")
	}
	t.APIKey = value
	rctx, err := s.sec.HandleCookieAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}
func (s *Server) securityJwtToken(ctx context.Context, operationName string, req *http.Request) (context.Context, bool, error) {
	var t JwtToken
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	rctx, err := s.sec.HandleJwtToken(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// APIToken provides api_token security value.
	APIToken(ctx context.Context, operationName string) (APIToken, error)
	// CookieAuth provides cookie_auth security value.
	CookieAuth(ctx context.Context, operationName string) (CookieAuth, error)
	// JwtToken provides jwt_token security value.
	JwtToken(ctx context.Context, operationName string) (JwtToken, error)
}

func (s *Client) securityAPIToken(ctx context.Context, operationName string, req *http.Request) error {
	t, err := s.sec.APIToken(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"APIToken\"")
	}
	req.Header.Set("x-medusa-access-token", t.APIKey)
	return nil
}
func (s *Client) securityCookieAuth(ctx context.Context, operationName string, req *http.Request) error {
	t, err := s.sec.CookieAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"CookieAuth\"")
	}
	req.AddCookie(&http.Cookie{
		Name:  "connect.sid",
		Value: t.APIKey,
	})
	return nil
}
func (s *Client) securityJwtToken(ctx context.Context, operationName string, req *http.Request) error {
	t, err := s.sec.JwtToken(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"JwtToken\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
